//
// Copyright (c) DeRec Alliance and its Contributors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: communicationinfo.proto

package derecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommunicationInfoKeyValue represents a single application-defined
// key-value pair used to convey user-facing identification data.
//
// # Purpose
//
// This structure is intended for:
//
// - displaying human-readable information to users during pairing
// - helping users identify and confirm counterparties
// - providing contextual metadata for UI/UX purposes
//
// # Semantics
//
// - The `key` is an application-defined identifier (e.g., "name", "phone")
// - The `value` contains the associated data, either as a string or raw bytes
//
// The protocol does not interpret these fields; they are opaque to the
// DeRec protocol and are only intended for application-level use.
//
// # Encoding
//
// Exactly one of the `value` fields MUST be set.
//
// Implementations SHOULD:
//
// - prefer `stringValue` for human-readable data
// - use `bytesValue` for structured or binary data (e.g., encoded identifiers)
//
// # Interoperability
//
// Applications SHOULD use consistent and well-known keys where possible
// (e.g., "name", "email", "phone") to improve cross-implementation UX,
// but no global registry is enforced by the protocol.
type CommunicationInfoKeyValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application-defined key identifying the type of information.
	//
	// Examples include "name", "email", "phone", or "accountId".
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Value associated with the key.
	//
	// Exactly one of the following fields MUST be set.
	//
	// Types that are valid to be assigned to Value:
	//
	//	*CommunicationInfoKeyValue_StringValue
	//	*CommunicationInfoKeyValue_BytesValue
	Value         isCommunicationInfoKeyValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommunicationInfoKeyValue) Reset() {
	*x = CommunicationInfoKeyValue{}
	mi := &file_communicationinfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunicationInfoKeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunicationInfoKeyValue) ProtoMessage() {}

func (x *CommunicationInfoKeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_communicationinfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunicationInfoKeyValue.ProtoReflect.Descriptor instead.
func (*CommunicationInfoKeyValue) Descriptor() ([]byte, []int) {
	return file_communicationinfo_proto_rawDescGZIP(), []int{0}
}

func (x *CommunicationInfoKeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CommunicationInfoKeyValue) GetValue() isCommunicationInfoKeyValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CommunicationInfoKeyValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*CommunicationInfoKeyValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *CommunicationInfoKeyValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*CommunicationInfoKeyValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

type isCommunicationInfoKeyValue_Value interface {
	isCommunicationInfoKeyValue_Value()
}

type CommunicationInfoKeyValue_StringValue struct {
	// Human-readable string value.
	//
	// This is the preferred representation for most user-facing data.
	StringValue string `protobuf:"bytes,2,opt,name=stringValue,proto3,oneof"`
}

type CommunicationInfoKeyValue_BytesValue struct {
	// Binary value.
	//
	// May be used for structured or encoded data that is not naturally
	// represented as a string.
	BytesValue []byte `protobuf:"bytes,3,opt,name=bytesValue,proto3,oneof"`
}

func (*CommunicationInfoKeyValue_StringValue) isCommunicationInfoKeyValue_Value() {}

func (*CommunicationInfoKeyValue_BytesValue) isCommunicationInfoKeyValue_Value() {}

// CommunicationInfo contains application-level identifying information
// about a participant (Owner or Helper).
//
// # Purpose
//
// This message is used to:
//
// - present identifying details to users during pairing
// - assist users in verifying the identity of the counterparty
// - provide contextual metadata for UI display
//
// # Semantics
//
// - The contents are entirely application-defined
// - The protocol does not validate, interpret, or enforce any schema
// - Entries are independent key-value pairs
//
// # Security Considerations
//
//   - This data MUST NOT be relied upon for authentication
//   - Authentication is handled outside the protocol (e.g., in-person,
//     KYC, or application-specific mechanisms)
//
// # Privacy Considerations
//
//   - Applications SHOULD avoid including sensitive information unless
//     necessary for the user experience
//   - Users should be informed about what data is being shared
//
// # Interoperability
//
// While no schema is enforced, using common keys improves usability
// across implementations.
type CommunicationInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of key-value entries describing the participant.
	//
	// Each entry represents one piece of identifying information.
	CommunicationInfoEntries []*CommunicationInfoKeyValue `protobuf:"bytes,1,rep,name=communicationInfoEntries,proto3" json:"communicationInfoEntries,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CommunicationInfo) Reset() {
	*x = CommunicationInfo{}
	mi := &file_communicationinfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunicationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunicationInfo) ProtoMessage() {}

func (x *CommunicationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_communicationinfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunicationInfo.ProtoReflect.Descriptor instead.
func (*CommunicationInfo) Descriptor() ([]byte, []int) {
	return file_communicationinfo_proto_rawDescGZIP(), []int{1}
}

func (x *CommunicationInfo) GetCommunicationInfoEntries() []*CommunicationInfoKeyValue {
	if x != nil {
		return x.CommunicationInfoEntries
	}
	return nil
}

var File_communicationinfo_proto protoreflect.FileDescriptor

const file_communicationinfo_proto_rawDesc = "" +
	"\n" +
	"\x17communicationinfo.proto\x12 org.derecalliance.derec.protobuf\"|\n" +
	"\x19CommunicationInfoKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\vstringValue\x18\x02 \x01(\tH\x00R\vstringValue\x12 \n" +
	"\n" +
	"bytesValue\x18\x03 \x01(\fH\x00R\n" +
	"bytesValueB\a\n" +
	"\x05value\"\x8c\x01\n" +
	"\x11CommunicationInfo\x12w\n" +
	"\x18communicationInfoEntries\x18\x01 \x03(\v2;.org.derecalliance.derec.protobuf.CommunicationInfoKeyValueR\x18communicationInfoEntriesb\x06proto3"

var (
	file_communicationinfo_proto_rawDescOnce sync.Once
	file_communicationinfo_proto_rawDescData []byte
)

func file_communicationinfo_proto_rawDescGZIP() []byte {
	file_communicationinfo_proto_rawDescOnce.Do(func() {
		file_communicationinfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_communicationinfo_proto_rawDesc), len(file_communicationinfo_proto_rawDesc)))
	})
	return file_communicationinfo_proto_rawDescData
}

var file_communicationinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_communicationinfo_proto_goTypes = []any{
	(*CommunicationInfoKeyValue)(nil), // 0: org.derecalliance.derec.protobuf.CommunicationInfoKeyValue
	(*CommunicationInfo)(nil),         // 1: org.derecalliance.derec.protobuf.CommunicationInfo
}
var file_communicationinfo_proto_depIdxs = []int32{
	0, // 0: org.derecalliance.derec.protobuf.CommunicationInfo.communicationInfoEntries:type_name -> org.derecalliance.derec.protobuf.CommunicationInfoKeyValue
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_communicationinfo_proto_init() }
func file_communicationinfo_proto_init() {
	if File_communicationinfo_proto != nil {
		return
	}
	file_communicationinfo_proto_msgTypes[0].OneofWrappers = []any{
		(*CommunicationInfoKeyValue_StringValue)(nil),
		(*CommunicationInfoKeyValue_BytesValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_communicationinfo_proto_rawDesc), len(file_communicationinfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_communicationinfo_proto_goTypes,
		DependencyIndexes: file_communicationinfo_proto_depIdxs,
		MessageInfos:      file_communicationinfo_proto_msgTypes,
	}.Build()
	File_communicationinfo_proto = out.File
	file_communicationinfo_proto_goTypes = nil
	file_communicationinfo_proto_depIdxs = nil
}
