//
// Copyright (c) DeRec Alliance and its Contributors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: committedderecshare.proto

package derecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommittedDeRecShare represents a DeRec share that has been committed and
// is ready to be given to a helper for storage.
//
// During recovery, this protobuf message is returned.
//
// The commitment uses a Merkle tree. The hash of the share given to each
// helper forms a leaf in the tree. Each leaf and internal node hash is a
// SHA-384 hash.
//
// The Merkle path from a leaf to the root (i.e., the sibling nodes along
// that route) is called merklePath. The root hash is referred to as the
// "commitment".
type CommittedDeRecShare struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protobuf serialization of DeRecShare.
	DeRecShare []byte `protobuf:"bytes,1,opt,name=deRecShare,proto3" json:"deRecShare,omitempty"`
	// The Merkle root.
	Commitment []byte `protobuf:"bytes,2,opt,name=commitment,proto3" json:"commitment,omitempty"`
	// The bottom-up Merkle path from the leaf to the root.
	MerklePath    []*CommittedDeRecShare_SiblingHash `protobuf:"bytes,3,rep,name=merklePath,proto3" json:"merklePath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommittedDeRecShare) Reset() {
	*x = CommittedDeRecShare{}
	mi := &file_committedderecshare_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommittedDeRecShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommittedDeRecShare) ProtoMessage() {}

func (x *CommittedDeRecShare) ProtoReflect() protoreflect.Message {
	mi := &file_committedderecshare_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommittedDeRecShare.ProtoReflect.Descriptor instead.
func (*CommittedDeRecShare) Descriptor() ([]byte, []int) {
	return file_committedderecshare_proto_rawDescGZIP(), []int{0}
}

func (x *CommittedDeRecShare) GetDeRecShare() []byte {
	if x != nil {
		return x.DeRecShare
	}
	return nil
}

func (x *CommittedDeRecShare) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *CommittedDeRecShare) GetMerklePath() []*CommittedDeRecShare_SiblingHash {
	if x != nil {
		return x.MerklePath
	}
	return nil
}

// DeRecShare contains the information that a sharer provides to a helper.
//
// The sharer first generates a random AES-256 key k and uses it to
// AES-GCM encrypt the secret. A random polynomial f is generated such
// that f(0) = k. The polynomial is then evaluated at a random x value
// for the intended helper, and the share contains the value y where
// f(x) = y.
//
// The computation should be done in GF(p), where p is the smallest
// 256-bit prime. The degree of the polynomial determines the threshold
// number of helpers required to reconstruct the secret.
//
// The message also includes the secretId and the share version number,
// because they must be serialized together with the share so that they
// are covered by the same signature.
type DeRecShare struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The result of serializing the secret to be shared and encrypting it
	// with a randomly generated AES-256 key.
	EncryptedSecret []byte `protobuf:"bytes,1,opt,name=encryptedSecret,proto3" json:"encryptedSecret,omitempty"`
	// Random 256-bit integer encoded as two's complement, big-endian.
	X []byte `protobuf:"bytes,2,opt,name=x,proto3" json:"x,omitempty"`
	// The value y = f(x).
	Y []byte `protobuf:"bytes,3,opt,name=y,proto3" json:"y,omitempty"`
	// Numeric identifier of the secret associated with the share.
	//
	// Must be unique for each secret created by a sharer.
	SecretId uint64 `protobuf:"varint,4,opt,name=secretId,proto3" json:"secretId,omitempty"`
	// Version number of the share.
	//
	// A helper is entitled to ignore any StoreShareRequestMessage whose
	// version is less than or equal to the last seen version.
	Version       uint32 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeRecShare) Reset() {
	*x = DeRecShare{}
	mi := &file_committedderecshare_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeRecShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeRecShare) ProtoMessage() {}

func (x *DeRecShare) ProtoReflect() protoreflect.Message {
	mi := &file_committedderecshare_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeRecShare.ProtoReflect.Descriptor instead.
func (*DeRecShare) Descriptor() ([]byte, []int) {
	return file_committedderecshare_proto_rawDescGZIP(), []int{1}
}

func (x *DeRecShare) GetEncryptedSecret() []byte {
	if x != nil {
		return x.EncryptedSecret
	}
	return nil
}

func (x *DeRecShare) GetX() []byte {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *DeRecShare) GetY() []byte {
	if x != nil {
		return x.Y
	}
	return nil
}

func (x *DeRecShare) GetSecretId() uint64 {
	if x != nil {
		return x.SecretId
	}
	return 0
}

func (x *DeRecShare) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Represents a leaf or interior node in the Merkle path.
// isLeft is true if the sibling is a left child.
type CommittedDeRecShare_SiblingHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLeft        bool                   `protobuf:"varint,1,opt,name=isLeft,proto3" json:"isLeft,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommittedDeRecShare_SiblingHash) Reset() {
	*x = CommittedDeRecShare_SiblingHash{}
	mi := &file_committedderecshare_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommittedDeRecShare_SiblingHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommittedDeRecShare_SiblingHash) ProtoMessage() {}

func (x *CommittedDeRecShare_SiblingHash) ProtoReflect() protoreflect.Message {
	mi := &file_committedderecshare_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommittedDeRecShare_SiblingHash.ProtoReflect.Descriptor instead.
func (*CommittedDeRecShare_SiblingHash) Descriptor() ([]byte, []int) {
	return file_committedderecshare_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CommittedDeRecShare_SiblingHash) GetIsLeft() bool {
	if x != nil {
		return x.IsLeft
	}
	return false
}

func (x *CommittedDeRecShare_SiblingHash) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

var File_committedderecshare_proto protoreflect.FileDescriptor

const file_committedderecshare_proto_rawDesc = "" +
	"\n" +
	"\x19committedderecshare.proto\x12 org.derecalliance.derec.protobuf\"\xf3\x01\n" +
	"\x13CommittedDeRecShare\x12\x1e\n" +
	"\n" +
	"deRecShare\x18\x01 \x01(\fR\n" +
	"deRecShare\x12\x1e\n" +
	"\n" +
	"commitment\x18\x02 \x01(\fR\n" +
	"commitment\x12a\n" +
	"\n" +
	"merklePath\x18\x03 \x03(\v2A.org.derecalliance.derec.protobuf.CommittedDeRecShare.SiblingHashR\n" +
	"merklePath\x1a9\n" +
	"\vSiblingHash\x12\x16\n" +
	"\x06isLeft\x18\x01 \x01(\bR\x06isLeft\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"\x88\x01\n" +
	"\n" +
	"DeRecShare\x12(\n" +
	"\x0fencryptedSecret\x18\x01 \x01(\fR\x0fencryptedSecret\x12\f\n" +
	"\x01x\x18\x02 \x01(\fR\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\fR\x01y\x12\x1a\n" +
	"\bsecretId\x18\x04 \x01(\x04R\bsecretId\x12\x18\n" +
	"\aversion\x18\x05 \x01(\rR\aversionb\x06proto3"

var (
	file_committedderecshare_proto_rawDescOnce sync.Once
	file_committedderecshare_proto_rawDescData []byte
)

func file_committedderecshare_proto_rawDescGZIP() []byte {
	file_committedderecshare_proto_rawDescOnce.Do(func() {
		file_committedderecshare_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_committedderecshare_proto_rawDesc), len(file_committedderecshare_proto_rawDesc)))
	})
	return file_committedderecshare_proto_rawDescData
}

var file_committedderecshare_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_committedderecshare_proto_goTypes = []any{
	(*CommittedDeRecShare)(nil),             // 0: org.derecalliance.derec.protobuf.CommittedDeRecShare
	(*DeRecShare)(nil),                      // 1: org.derecalliance.derec.protobuf.DeRecShare
	(*CommittedDeRecShare_SiblingHash)(nil), // 2: org.derecalliance.derec.protobuf.CommittedDeRecShare.SiblingHash
}
var file_committedderecshare_proto_depIdxs = []int32{
	2, // 0: org.derecalliance.derec.protobuf.CommittedDeRecShare.merklePath:type_name -> org.derecalliance.derec.protobuf.CommittedDeRecShare.SiblingHash
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_committedderecshare_proto_init() }
func file_committedderecshare_proto_init() {
	if File_committedderecshare_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_committedderecshare_proto_rawDesc), len(file_committedderecshare_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_committedderecshare_proto_goTypes,
		DependencyIndexes: file_committedderecshare_proto_depIdxs,
		MessageInfos:      file_committedderecshare_proto_msgTypes,
	}.Build()
	File_committedderecshare_proto = out.File
	file_committedderecshare_proto_goTypes = nil
	file_committedderecshare_proto_depIdxs = nil
}
