//
// Copyright (c) DeRec Alliance and its Contributors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: contact.proto

package derecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Selects the delivery mode for the public encryption material in
// `ContactMessage`. See `ContactMessage` for details.
type ContactMode int32

const (
	// Default. `mlkemEncapsulationKey` and `eciesPublicKey` are inlined
	// in the contact.
	ContactMode_INLINE_KEYS ContactMode = 0
	// `contactBindingHash` is inlined in the contact; keys are obtained via
	// `PrePairRequest` / `PrePairResponse` and verified against the hash.
	ContactMode_HASHED_KEYS ContactMode = 1
	// No key material and no hash are inlined. The contact carries only
	// `channelId`, `nonce`, and `transportProtocol`; the contact creator
	// generates key material on the fly when the corresponding
	// `PrePairRequest` arrives. Only appropriate when the out-of-band
	// delivery channel is fully trusted, and the channel stays unusable
	// until both sides confirm the fingerprint out of band — nothing else
	// binds the published keys to the contact.
	ContactMode_NO_KEYS ContactMode = 2
)

// Enum value maps for ContactMode.
var (
	ContactMode_name = map[int32]string{
		0: "INLINE_KEYS",
		1: "HASHED_KEYS",
		2: "NO_KEYS",
	}
	ContactMode_value = map[string]int32{
		"INLINE_KEYS": 0,
		"HASHED_KEYS": 1,
		"NO_KEYS":     2,
	}
)

func (x ContactMode) Enum() *ContactMode {
	p := new(ContactMode)
	*p = x
	return p
}

func (x ContactMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContactMode) Descriptor() protoreflect.EnumDescriptor {
	return file_contact_proto_enumTypes[0].Descriptor()
}

func (ContactMode) Type() protoreflect.EnumType {
	return &file_contact_proto_enumTypes[0]
}

func (x ContactMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContactMode.Descriptor instead.
func (ContactMode) EnumDescriptor() ([]byte, []int) {
	return file_contact_proto_rawDescGZIP(), []int{0}
}

type ContactMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Selects how the public encryption material is delivered. Defaults to
	// `INLINE_KEYS` (current behavior) when unset.
	ContactMode ContactMode `protobuf:"varint,1,opt,name=contactMode,proto3,enum=org.derecalliance.derec.protobuf.ContactMode" json:"contactMode,omitempty"`
	// Serialized ML-KEM-768 encapsulation key.
	//
	// Present only when `contactMode == INLINE_KEYS`. Used by
	// the recipient to construct the initial pairing message.
	MlkemEncapsulationKey []byte `protobuf:"bytes,2,opt,name=mlkemEncapsulationKey,proto3,oneof" json:"mlkemEncapsulationKey,omitempty"`
	// Serialized ECIES public key.
	//
	// Present only when `contactMode == INLINE_KEYS`. Used by
	// the recipient to construct the initial pairing message.
	EciesPublicKey []byte `protobuf:"bytes,3,opt,name=eciesPublicKey,proto3,oneof" json:"eciesPublicKey,omitempty"`
	// SHA-384 commitment to the public encryption material.
	//
	// Present only when `contactMode == HASHED_KEYS`. Computed
	// as:
	//
	// ```text
	// SHA-384(
	//
	//	mlkemEncapsulationKey
	//	|| eciesPublicKey
	//	|| u64_be(nonce)
	//	|| u64_be(channelId)
	//
	// )
	// ```
	//
	// The recipient obtains the actual keys via `PrePairRequest` and
	// recomputes this hash to confirm integrity before proceeding to
	// `PairRequestMessage`.
	ContactBindingHash []byte `protobuf:"bytes,4,opt,name=contactBindingHash,proto3,oneof" json:"contactBindingHash,omitempty"`
	// Channel identifier associated with this contact.
	//
	// This value identifies the communication channel that the creator of this
	// ContactMessage expects to use for the new pairing. After receiving this
	// contact, the initiating party includes this channelId in subsequent
	// protocol messages sent to the contact creator.
	//
	// The recipient uses this identifier to determine which local key material
	// and pairing state should be used when processing the message.
	//
	// If an implementation generates multiple pending contact records or
	// multiple encryption key pairs for different pairing attempts, it should
	// retain the mapping from channelId to the corresponding local state so it
	// can process inbound messages without trial decryption across all keys.
	//
	// This value MUST be unique within the scope required by the implementation
	// to disambiguate concurrent or stored pairing sessions.
	ChannelId uint64 `protobuf:"varint,5,opt,name=channelId,proto3" json:"channelId,omitempty"`
	// Random nonce used to bind the pairing request to this contact exchange.
	//
	// The initiator includes this value in the pairing request so the creator
	// of the ContactMessage can confirm that the request corresponds to the
	// same out-of-band contact information that was just shared.
	//
	// This helps the application detect mismatched, stale, or spoofed pairing
	// attempts during the bootstrap phase.
	//
	// Applications may choose to reveal this nonce only after sufficient
	// out-of-band authentication has taken place.
	Nonce uint64 `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Transport information used to reach the creator of this contact.
	//
	// This specifies both:
	//
	//   - the endpoint to which the first protocol message should be sent
	//   - the transport protocol that determines how that endpoint is interpreted
	//     and used
	//
	// The initiating party uses this field to deliver the initial pairing
	// request. Subsequent protocol exchanges may continue using the same
	// transport information or updated transport details, depending on the
	// protocol and application behavior.
	//
	// Deprecated: superseded by `supportedTransports`, which carries every
	// endpoint rather than one.
	//
	// **Reading this field directly is now incorrect.** Its meaning narrowed
	// from "the endpoint" to "one entry of a list, and possibly absent": a
	// creator that has moved past this field advertises only
	// `supportedTransports`. A reader that was correct before this release is
	// a bug now — it rejects, or fails to reach, a peer that is offering it a
	// perfectly good endpoint. Resolve both spellings instead of reading
	// either: `advertised_endpoints()` (Rust and TypeScript),
	// `AdvertisedEndpoints()` (Go), `AdvertisedEndpoints()` (.NET).
	//
	// Senders still populate it: a sender that sets `supportedTransports`
	// MUST also set this to a single best-compatibility choice, so
	// implementations predating the list still pair.
	//
	// **Scheduled for removal in v0.0.5.**
	//
	// Deprecated: Marked as deprecated in contact.proto.
	TransportProtocol *TransportProtocol `protobuf:"bytes,7,opt,name=transportProtocol,proto3" json:"transportProtocol,omitempty"`
	// Timestamp indicating when the sender created this message.
	//
	// This value is expressed in UTC and can be used for:
	//
	// - replay detection
	// - timeout handling
	// - logging and observability
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Every transport endpoint the creator of this contact can be reached on.
	//
	// Each entry is a complete endpoint: a URI plus the protocol that says
	// how to interpret it. The list is written in the creator's own
	// preference order.
	//
	// # Selection is the recipient's
	//
	// A recipient picks whichever entry suits it, ordered by its **own**
	// preference rather than the sender's. The order here expresses
	// availability, not a ranking the recipient must honor.
	//
	// # Compatibility
	//
	// Absent means "only `transportProtocol` is offered", which is how every
	// implementation predating this field behaves. A sender populating this
	// list MUST also set `transportProtocol` to a single best-compatibility
	// choice so those implementations still pair.
	//
	// # Security
	//
	// `contactBindingHash` does not cover this field, exactly as it does not
	// cover `transportProtocol`. An attacker able to rewrite an
	// out-of-band contact can therefore remove entries. Removing the secure
	// ones leaves only plaintext, which the recipient's transport policy
	// refuses unless plaintext has been explicitly opted into. DeRec messages
	// are signed and encrypted at the application layer on every transport,
	// so substituting one secure transport for another is not a loss of
	// confidentiality or authenticity.
	SupportedTransports []*TransportProtocol `protobuf:"bytes,9,rep,name=supportedTransports,proto3" json:"supportedTransports,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ContactMessage) Reset() {
	*x = ContactMessage{}
	mi := &file_contact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactMessage) ProtoMessage() {}

func (x *ContactMessage) ProtoReflect() protoreflect.Message {
	mi := &file_contact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactMessage.ProtoReflect.Descriptor instead.
func (*ContactMessage) Descriptor() ([]byte, []int) {
	return file_contact_proto_rawDescGZIP(), []int{0}
}

func (x *ContactMessage) GetContactMode() ContactMode {
	if x != nil {
		return x.ContactMode
	}
	return ContactMode_INLINE_KEYS
}

func (x *ContactMessage) GetMlkemEncapsulationKey() []byte {
	if x != nil {
		return x.MlkemEncapsulationKey
	}
	return nil
}

func (x *ContactMessage) GetEciesPublicKey() []byte {
	if x != nil {
		return x.EciesPublicKey
	}
	return nil
}

func (x *ContactMessage) GetContactBindingHash() []byte {
	if x != nil {
		return x.ContactBindingHash
	}
	return nil
}

func (x *ContactMessage) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ContactMessage) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

// Deprecated: Marked as deprecated in contact.proto.
func (x *ContactMessage) GetTransportProtocol() *TransportProtocol {
	if x != nil {
		return x.TransportProtocol
	}
	return nil
}

func (x *ContactMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ContactMessage) GetSupportedTransports() []*TransportProtocol {
	if x != nil {
		return x.SupportedTransports
	}
	return nil
}

var File_contact_proto protoreflect.FileDescriptor

const file_contact_proto_rawDesc = "" +
	"\n" +
	"\rcontact.proto\x12 org.derecalliance.derec.protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17transportprotocol.proto\"\xfe\x04\n" +
	"\x0eContactMessage\x12O\n" +
	"\vcontactMode\x18\x01 \x01(\x0e2-.org.derecalliance.derec.protobuf.ContactModeR\vcontactMode\x129\n" +
	"\x15mlkemEncapsulationKey\x18\x02 \x01(\fH\x00R\x15mlkemEncapsulationKey\x88\x01\x01\x12+\n" +
	"\x0eeciesPublicKey\x18\x03 \x01(\fH\x01R\x0eeciesPublicKey\x88\x01\x01\x123\n" +
	"\x12contactBindingHash\x18\x04 \x01(\fH\x02R\x12contactBindingHash\x88\x01\x01\x12\x1c\n" +
	"\tchannelId\x18\x05 \x01(\x04R\tchannelId\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\x04R\x05nonce\x12e\n" +
	"\x11transportProtocol\x18\a \x01(\v23.org.derecalliance.derec.protobuf.TransportProtocolB\x02\x18\x01R\x11transportProtocol\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12e\n" +
	"\x13supportedTransports\x18\t \x03(\v23.org.derecalliance.derec.protobuf.TransportProtocolR\x13supportedTransportsB\x18\n" +
	"\x16_mlkemEncapsulationKeyB\x11\n" +
	"\x0f_eciesPublicKeyB\x15\n" +
	"\x13_contactBindingHash*<\n" +
	"\vContactMode\x12\x0f\n" +
	"\vINLINE_KEYS\x10\x00\x12\x0f\n" +
	"\vHASHED_KEYS\x10\x01\x12\v\n" +
	"\aNO_KEYS\x10\x02b\x06proto3"

var (
	file_contact_proto_rawDescOnce sync.Once
	file_contact_proto_rawDescData []byte
)

func file_contact_proto_rawDescGZIP() []byte {
	file_contact_proto_rawDescOnce.Do(func() {
		file_contact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contact_proto_rawDesc), len(file_contact_proto_rawDesc)))
	})
	return file_contact_proto_rawDescData
}

var file_contact_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contact_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_contact_proto_goTypes = []any{
	(ContactMode)(0),              // 0: org.derecalliance.derec.protobuf.ContactMode
	(*ContactMessage)(nil),        // 1: org.derecalliance.derec.protobuf.ContactMessage
	(*TransportProtocol)(nil),     // 2: org.derecalliance.derec.protobuf.TransportProtocol
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_contact_proto_depIdxs = []int32{
	0, // 0: org.derecalliance.derec.protobuf.ContactMessage.contactMode:type_name -> org.derecalliance.derec.protobuf.ContactMode
	2, // 1: org.derecalliance.derec.protobuf.ContactMessage.transportProtocol:type_name -> org.derecalliance.derec.protobuf.TransportProtocol
	3, // 2: org.derecalliance.derec.protobuf.ContactMessage.timestamp:type_name -> google.protobuf.Timestamp
	2, // 3: org.derecalliance.derec.protobuf.ContactMessage.supportedTransports:type_name -> org.derecalliance.derec.protobuf.TransportProtocol
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_contact_proto_init() }
func file_contact_proto_init() {
	if File_contact_proto != nil {
		return
	}
	file_transportprotocol_proto_init()
	file_contact_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contact_proto_rawDesc), len(file_contact_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contact_proto_goTypes,
		DependencyIndexes: file_contact_proto_depIdxs,
		EnumInfos:         file_contact_proto_enumTypes,
		MessageInfos:      file_contact_proto_msgTypes,
	}.Build()
	File_contact_proto = out.File
	file_contact_proto_goTypes = nil
	file_contact_proto_depIdxs = nil
}
