//
// Copyright (c) DeRec Alliance and its Contributors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: derecmessage.proto

package derecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeRecMessage is the top-level protocol envelope for all DeRec messages,
// except ContactMessage which is exchanged out-of-band during pairing.
//
// This message represents the unit of communication between an Owner and a
// Helper once a secure channel has been established. Every protocol exchange
// (pairing, sharing, verification, recovery, etc.) is carried inside this
// envelope.
//
// # Security Model
//
// The DeRecMessage envelope itself is not responsible for confidentiality or
// authenticity. Instead:
//
// - The `message` field contains encrypted bytes representing the inner message
// - Encryption is applied at the payload level prior to transport
//
// Implementations MUST ensure that:
//
// - The inner message is encrypted using the agreed channel keys
// - The envelope metadata is treated as untrusted until the payload is verified
//
// # Semantics
//
// A DeRecMessage provides:
//
// - protocol versioning information for compatibility handling
// - ordering guarantees via a monotonically increasing sequence number
// - channel identification for routing and key selection
// - a timestamp for replay protection and observability
// - an encrypted payload containing exactly one protocol message
//
// The envelope is transport-agnostic and can be delivered over any supported
// transport (e.g., HTTPS, message queues), as defined by TransportProtocol.
//
// # Ordering and Idempotency
//
// Communication follows a request/response pattern:
//
// - The Owner sends a request message
// - The Helper replies with a corresponding response
//
// The `sequence` field is used to:
//
// - enforce message ordering
// - detect duplicates or out-of-order delivery
// - support replay protection
//
// Implementations SHOULD treat messages as idempotent and be resilient to
// retries and duplicate deliveries.
//
// # Key Rotation
//
// The sequence number may also be used as a trigger for automatic key rotation.
// When a configured threshold is reached, implementations MAY initiate a key
// rotation flow to maintain forward secrecy.
//
// # Versioning
//
// The protocolVersionMajor and protocolVersionMinor fields allow peers to:
//
// - detect incompatible protocol versions
// - apply backward-compatible parsing logic when possible
//
// Implementations MUST define behavior for handling version mismatches.
//
// # Payload Encoding
//
// The `message` field contains encrypted raw bytes. When decrypted, these bytes
// MUST deserialize into a MessageBody, which contains exactly one concrete
// protocol message.
//
// The oneof structure ensures that each DeRecMessage carries a single logical
// operation.
type DeRecMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DeRec protocol major version.
	//
	// Incremented for breaking changes that are not backward compatible.
	ProtocolVersionMajor uint32 `protobuf:"varint,1,opt,name=protocolVersionMajor,proto3" json:"protocolVersionMajor,omitempty"`
	// DeRec protocol minor version.
	//
	// Incremented for backward-compatible changes such as adding new fields
	// or message types.
	ProtocolVersionMinor uint32 `protobuf:"varint,2,opt,name=protocolVersionMinor,proto3" json:"protocolVersionMinor,omitempty"`
	// Monotonically increasing message sequence number.
	//
	// This value increments by 1 for each message sent on a given channel.
	// It is used to:
	//
	// - enforce ordering
	// - detect duplicates or missing messages
	// - support replay protection
	//
	// Implementations MAY also use this value to trigger automatic key rotation
	// once a predefined threshold is reached.
	Sequence uint32 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Channel identifier associated with this communication session.
	//
	// This value uniquely identifies the logical channel between an Owner and
	// a Helper for a given secret. It is established during pairing and used
	// thereafter to:
	//
	// - route messages to the correct channel state
	// - select the appropriate cryptographic keys
	//
	// This MUST match the channelId exchanged during the ContactMessage phase.
	ChannelId uint64 `protobuf:"varint,4,opt,name=channelId,proto3" json:"channelId,omitempty"`
	// Timestamp indicating when the sender created this message.
	//
	// This value is expressed in UTC and can be used for:
	//
	// - replay detection
	// - timeout handling
	// - logging and observability
	//
	// Implementations SHOULD NOT rely solely on this value for security-critical
	// decisions without additional protections.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Encrypted message payload.
	//
	// This field contains the encrypted bytes of a serialized MessageBody.
	// The encryption scheme and key material are defined by the pairing process
	// and subsequent key management flows.
	//
	// Upon decryption, this field MUST deserialize into a valid MessageBody
	// containing exactly one protocol message.
	Message []byte `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	// Application-supplied correlation token, echoed verbatim by the
	// responder on the matching response envelope.
	//
	// # Purpose
	//
	// Lets the side that originated a request match the eventual response to
	// the in-flight request that produced it, even when:
	//
	// - multiple requests are outstanding on the same channel,
	// - responses arrive out of order with respect to send order,
	// - the responder takes arbitrary time to reply.
	//
	// # Semantics
	//
	//   - On a request envelope: the requester sets this to any value it can
	//     use to correlate the response back to the originating call site. A
	//     random `uint64` is a typical choice; collisions are unlikely at any
	//     realistic concurrency level.
	//   - On a response envelope: the responder MUST copy the request's
	//     `traceId` verbatim. The library does this automatically in every
	//     response producer.
	//   - Zero (the protobuf default when unset) is treated as "no correlation
	//     requested." Responders still echo the zero on the response envelope;
	//     requesters that do not care about correlation simply ignore the
	//     field.
	//
	// # Privacy
	//
	// This field is plaintext on the wire (the envelope is not encrypted).
	// The token itself is opaque, so it carries no information about either
	// peer's identity or intent — it is purely a correlation handle. Passive
	// observers could already correlate request/response pairs by channelId
	// and timing; `traceId` does not add to that exposure.
	TraceId       uint64 `protobuf:"varint,7,opt,name=traceId,proto3" json:"traceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeRecMessage) Reset() {
	*x = DeRecMessage{}
	mi := &file_derecmessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeRecMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeRecMessage) ProtoMessage() {}

func (x *DeRecMessage) ProtoReflect() protoreflect.Message {
	mi := &file_derecmessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeRecMessage.ProtoReflect.Descriptor instead.
func (*DeRecMessage) Descriptor() ([]byte, []int) {
	return file_derecmessage_proto_rawDescGZIP(), []int{0}
}

func (x *DeRecMessage) GetProtocolVersionMajor() uint32 {
	if x != nil {
		return x.ProtocolVersionMajor
	}
	return 0
}

func (x *DeRecMessage) GetProtocolVersionMinor() uint32 {
	if x != nil {
		return x.ProtocolVersionMinor
	}
	return 0
}

func (x *DeRecMessage) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *DeRecMessage) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *DeRecMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DeRecMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *DeRecMessage) GetTraceId() uint64 {
	if x != nil {
		return x.TraceId
	}
	return 0
}

// MessageBody defines all possible DeRec protocol messages that can be
// transported inside the DeRecMessage envelope.
//
// Exactly one of the fields MUST be set when constructing a message.
type DeRecMessage_MessageBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*DeRecMessage_MessageBody_PairRequestMessage
	//	*DeRecMessage_MessageBody_PairResponseMessage
	//	*DeRecMessage_MessageBody_UnpairRequestMessage
	//	*DeRecMessage_MessageBody_UnpairResponseMessage
	//	*DeRecMessage_MessageBody_StoreShareRequestMessage
	//	*DeRecMessage_MessageBody_StoreShareResponseMessage
	//	*DeRecMessage_MessageBody_VerifyShareRequestMessage
	//	*DeRecMessage_MessageBody_VerifyShareResponseMessage
	//	*DeRecMessage_MessageBody_GetSecretIdsVersionsRequestMessage
	//	*DeRecMessage_MessageBody_GetSecretIdsVersionsResponseMessage
	//	*DeRecMessage_MessageBody_GetShareRequestMessage
	//	*DeRecMessage_MessageBody_GetShareResponseMessage
	//	*DeRecMessage_MessageBody_ErrorResponseMessage
	//	*DeRecMessage_MessageBody_UpdateChannelInfoRequestMessage
	//	*DeRecMessage_MessageBody_UpdateChannelInfoResponseMessage
	//	*DeRecMessage_MessageBody_PrePairRequestMessage
	//	*DeRecMessage_MessageBody_PrePairResponseMessage
	Body          isDeRecMessage_MessageBody_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeRecMessage_MessageBody) Reset() {
	*x = DeRecMessage_MessageBody{}
	mi := &file_derecmessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeRecMessage_MessageBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeRecMessage_MessageBody) ProtoMessage() {}

func (x *DeRecMessage_MessageBody) ProtoReflect() protoreflect.Message {
	mi := &file_derecmessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeRecMessage_MessageBody.ProtoReflect.Descriptor instead.
func (*DeRecMessage_MessageBody) Descriptor() ([]byte, []int) {
	return file_derecmessage_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DeRecMessage_MessageBody) GetBody() isDeRecMessage_MessageBody_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *DeRecMessage_MessageBody) GetPairRequestMessage() *PairRequestMessage {
	if x != nil {
		if x, ok := x.Body.(*DeRecMessage_MessageBody_PairRequestMessage); ok {
			return x.PairRequestMessage
		}
	}
	return nil
}

func (x *DeRecMessage_MessageBody) GetPairResponseMessage() *PairResponseMessage {
	if x != nil {
		if x, ok := x.Body.(*DeRecMessage_MessageBody_PairResponseMessage); ok {
			return x.PairResponseMessage
		}
	}
	return nil
}

func (x *DeRecMessage_MessageBody) GetUnpairRequestMessage() *UnpairRequestMessage {
	if x != nil {
		if x, ok := x.Body.(*DeRecMessage_MessageBody_UnpairRequestMessage); ok {
			return x.UnpairRequestMessage
		}
	}
	return nil
}

func (x *DeRecMessage_MessageBody) GetUnpairResponseMessage() *UnpairResponseMessage {
	if x != nil {
		if x, ok := x.Body.(*DeRecMessage_MessageBody_UnpairResponseMessage); ok {
			return x.UnpairResponseMessage
		}
	}
	return nil
}

func (x *DeRecMessage_MessageBody) GetStoreShareRequestMessage() *StoreShareRequestMessage {
	if x != nil {
		if x, ok := x.Body.(*DeRecMessage_MessageBody_StoreShareRequestMessage); ok {
			return x.StoreShareRequestMessage
		}
	}
	return nil
}

func (x *DeRecMessage_MessageBody) GetStoreShareResponseMessage() *StoreShareResponseMessage {
	if x != nil {
		if x, ok := x.Body.(*DeRecMessage_MessageBody_StoreShareResponseMessage); ok {
			return x.StoreShareResponseMessage
		}
	}
	return nil
}

func (x *DeRecMessage_MessageBody) GetVerifyShareRequestMessage() *VerifyShareRequestMessage {
	if x != nil {
		if x, ok := x.Body.(*DeRecMessage_MessageBody_VerifyShareRequestMessage); ok {
			return x.VerifyShareRequestMessage
		}
	}
	return nil
}

func (x *DeRecMessage_MessageBody) GetVerifyShareResponseMessage() *VerifyShareResponseMessage {
	if x != nil {
		if x, ok := x.Body.(*DeRecMessage_MessageBody_VerifyShareResponseMessage); ok {
			return x.VerifyShareResponseMessage
		}
	}
	return nil
}

func (x *DeRecMessage_MessageBody) GetGetSecretIdsVersionsRequestMessage() *GetSecretIdsVersionsRequestMessage {
	if x != nil {
		if x, ok := x.Body.(*DeRecMessage_MessageBody_GetSecretIdsVersionsRequestMessage); ok {
			return x.GetSecretIdsVersionsRequestMessage
		}
	}
	return nil
}

func (x *DeRecMessage_MessageBody) GetGetSecretIdsVersionsResponseMessage() *GetSecretIdsVersionsResponseMessage {
	if x != nil {
		if x, ok := x.Body.(*DeRecMessage_MessageBody_GetSecretIdsVersionsResponseMessage); ok {
			return x.GetSecretIdsVersionsResponseMessage
		}
	}
	return nil
}

func (x *DeRecMessage_MessageBody) GetGetShareRequestMessage() *GetShareRequestMessage {
	if x != nil {
		if x, ok := x.Body.(*DeRecMessage_MessageBody_GetShareRequestMessage); ok {
			return x.GetShareRequestMessage
		}
	}
	return nil
}

func (x *DeRecMessage_MessageBody) GetGetShareResponseMessage() *GetShareResponseMessage {
	if x != nil {
		if x, ok := x.Body.(*DeRecMessage_MessageBody_GetShareResponseMessage); ok {
			return x.GetShareResponseMessage
		}
	}
	return nil
}

func (x *DeRecMessage_MessageBody) GetErrorResponseMessage() *ErrorResponseMessage {
	if x != nil {
		if x, ok := x.Body.(*DeRecMessage_MessageBody_ErrorResponseMessage); ok {
			return x.ErrorResponseMessage
		}
	}
	return nil
}

func (x *DeRecMessage_MessageBody) GetUpdateChannelInfoRequestMessage() *UpdateChannelInfoRequestMessage {
	if x != nil {
		if x, ok := x.Body.(*DeRecMessage_MessageBody_UpdateChannelInfoRequestMessage); ok {
			return x.UpdateChannelInfoRequestMessage
		}
	}
	return nil
}

func (x *DeRecMessage_MessageBody) GetUpdateChannelInfoResponseMessage() *UpdateChannelInfoResponseMessage {
	if x != nil {
		if x, ok := x.Body.(*DeRecMessage_MessageBody_UpdateChannelInfoResponseMessage); ok {
			return x.UpdateChannelInfoResponseMessage
		}
	}
	return nil
}

func (x *DeRecMessage_MessageBody) GetPrePairRequestMessage() *PrePairRequestMessage {
	if x != nil {
		if x, ok := x.Body.(*DeRecMessage_MessageBody_PrePairRequestMessage); ok {
			return x.PrePairRequestMessage
		}
	}
	return nil
}

func (x *DeRecMessage_MessageBody) GetPrePairResponseMessage() *PrePairResponseMessage {
	if x != nil {
		if x, ok := x.Body.(*DeRecMessage_MessageBody_PrePairResponseMessage); ok {
			return x.PrePairResponseMessage
		}
	}
	return nil
}

type isDeRecMessage_MessageBody_Body interface {
	isDeRecMessage_MessageBody_Body()
}

type DeRecMessage_MessageBody_PairRequestMessage struct {
	PairRequestMessage *PairRequestMessage `protobuf:"bytes,1,opt,name=pairRequestMessage,proto3,oneof"`
}

type DeRecMessage_MessageBody_PairResponseMessage struct {
	PairResponseMessage *PairResponseMessage `protobuf:"bytes,2,opt,name=pairResponseMessage,proto3,oneof"`
}

type DeRecMessage_MessageBody_UnpairRequestMessage struct {
	UnpairRequestMessage *UnpairRequestMessage `protobuf:"bytes,3,opt,name=unpairRequestMessage,proto3,oneof"`
}

type DeRecMessage_MessageBody_UnpairResponseMessage struct {
	UnpairResponseMessage *UnpairResponseMessage `protobuf:"bytes,4,opt,name=unpairResponseMessage,proto3,oneof"`
}

type DeRecMessage_MessageBody_StoreShareRequestMessage struct {
	StoreShareRequestMessage *StoreShareRequestMessage `protobuf:"bytes,5,opt,name=storeShareRequestMessage,proto3,oneof"`
}

type DeRecMessage_MessageBody_StoreShareResponseMessage struct {
	StoreShareResponseMessage *StoreShareResponseMessage `protobuf:"bytes,6,opt,name=storeShareResponseMessage,proto3,oneof"`
}

type DeRecMessage_MessageBody_VerifyShareRequestMessage struct {
	VerifyShareRequestMessage *VerifyShareRequestMessage `protobuf:"bytes,7,opt,name=verifyShareRequestMessage,proto3,oneof"`
}

type DeRecMessage_MessageBody_VerifyShareResponseMessage struct {
	VerifyShareResponseMessage *VerifyShareResponseMessage `protobuf:"bytes,8,opt,name=verifyShareResponseMessage,proto3,oneof"`
}

type DeRecMessage_MessageBody_GetSecretIdsVersionsRequestMessage struct {
	GetSecretIdsVersionsRequestMessage *GetSecretIdsVersionsRequestMessage `protobuf:"bytes,9,opt,name=getSecretIdsVersionsRequestMessage,proto3,oneof"`
}

type DeRecMessage_MessageBody_GetSecretIdsVersionsResponseMessage struct {
	GetSecretIdsVersionsResponseMessage *GetSecretIdsVersionsResponseMessage `protobuf:"bytes,10,opt,name=getSecretIdsVersionsResponseMessage,proto3,oneof"`
}

type DeRecMessage_MessageBody_GetShareRequestMessage struct {
	GetShareRequestMessage *GetShareRequestMessage `protobuf:"bytes,11,opt,name=getShareRequestMessage,proto3,oneof"`
}

type DeRecMessage_MessageBody_GetShareResponseMessage struct {
	GetShareResponseMessage *GetShareResponseMessage `protobuf:"bytes,12,opt,name=getShareResponseMessage,proto3,oneof"`
}

type DeRecMessage_MessageBody_ErrorResponseMessage struct {
	ErrorResponseMessage *ErrorResponseMessage `protobuf:"bytes,13,opt,name=errorResponseMessage,proto3,oneof"`
}

type DeRecMessage_MessageBody_UpdateChannelInfoRequestMessage struct {
	UpdateChannelInfoRequestMessage *UpdateChannelInfoRequestMessage `protobuf:"bytes,14,opt,name=updateChannelInfoRequestMessage,proto3,oneof"`
}

type DeRecMessage_MessageBody_UpdateChannelInfoResponseMessage struct {
	UpdateChannelInfoResponseMessage *UpdateChannelInfoResponseMessage `protobuf:"bytes,15,opt,name=updateChannelInfoResponseMessage,proto3,oneof"`
}

type DeRecMessage_MessageBody_PrePairRequestMessage struct {
	PrePairRequestMessage *PrePairRequestMessage `protobuf:"bytes,16,opt,name=prePairRequestMessage,proto3,oneof"`
}

type DeRecMessage_MessageBody_PrePairResponseMessage struct {
	PrePairResponseMessage *PrePairResponseMessage `protobuf:"bytes,17,opt,name=prePairResponseMessage,proto3,oneof"`
}

func (*DeRecMessage_MessageBody_PairRequestMessage) isDeRecMessage_MessageBody_Body() {}

func (*DeRecMessage_MessageBody_PairResponseMessage) isDeRecMessage_MessageBody_Body() {}

func (*DeRecMessage_MessageBody_UnpairRequestMessage) isDeRecMessage_MessageBody_Body() {}

func (*DeRecMessage_MessageBody_UnpairResponseMessage) isDeRecMessage_MessageBody_Body() {}

func (*DeRecMessage_MessageBody_StoreShareRequestMessage) isDeRecMessage_MessageBody_Body() {}

func (*DeRecMessage_MessageBody_StoreShareResponseMessage) isDeRecMessage_MessageBody_Body() {}

func (*DeRecMessage_MessageBody_VerifyShareRequestMessage) isDeRecMessage_MessageBody_Body() {}

func (*DeRecMessage_MessageBody_VerifyShareResponseMessage) isDeRecMessage_MessageBody_Body() {}

func (*DeRecMessage_MessageBody_GetSecretIdsVersionsRequestMessage) isDeRecMessage_MessageBody_Body() {
}

func (*DeRecMessage_MessageBody_GetSecretIdsVersionsResponseMessage) isDeRecMessage_MessageBody_Body() {
}

func (*DeRecMessage_MessageBody_GetShareRequestMessage) isDeRecMessage_MessageBody_Body() {}

func (*DeRecMessage_MessageBody_GetShareResponseMessage) isDeRecMessage_MessageBody_Body() {}

func (*DeRecMessage_MessageBody_ErrorResponseMessage) isDeRecMessage_MessageBody_Body() {}

func (*DeRecMessage_MessageBody_UpdateChannelInfoRequestMessage) isDeRecMessage_MessageBody_Body() {}

func (*DeRecMessage_MessageBody_UpdateChannelInfoResponseMessage) isDeRecMessage_MessageBody_Body() {}

func (*DeRecMessage_MessageBody_PrePairRequestMessage) isDeRecMessage_MessageBody_Body() {}

func (*DeRecMessage_MessageBody_PrePairResponseMessage) isDeRecMessage_MessageBody_Body() {}

var File_derecmessage_proto protoreflect.FileDescriptor

const file_derecmessage_proto_rawDesc = "" +
	"\n" +
	"\x12derecmessage.proto\x12 org.derecalliance.derec.protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\n" +
	"pair.proto\x1a\funpair.proto\x1a\x10storeshare.proto\x1a\fverify.proto\x1a\x0egetshare.proto\x1a\x17secretidsversions.proto\x1a\x17updatechannelinfo.proto\x1a\rprepair.proto\x1a\verror.proto\"\xf2\x12\n" +
	"\fDeRecMessage\x122\n" +
	"\x14protocolVersionMajor\x18\x01 \x01(\rR\x14protocolVersionMajor\x122\n" +
	"\x14protocolVersionMinor\x18\x02 \x01(\rR\x14protocolVersionMinor\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\rR\bsequence\x12\x1c\n" +
	"\tchannelId\x18\x04 \x01(\x04R\tchannelId\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\amessage\x18\x06 \x01(\fR\amessage\x12\x18\n" +
	"\atraceId\x18\a \x01(\x04R\atraceId\x1a\xd1\x10\n" +
	"\vMessageBody\x12f\n" +
	"\x12pairRequestMessage\x18\x01 \x01(\v24.org.derecalliance.derec.protobuf.PairRequestMessageH\x00R\x12pairRequestMessage\x12i\n" +
	"\x13pairResponseMessage\x18\x02 \x01(\v25.org.derecalliance.derec.protobuf.PairResponseMessageH\x00R\x13pairResponseMessage\x12l\n" +
	"\x14unpairRequestMessage\x18\x03 \x01(\v26.org.derecalliance.derec.protobuf.UnpairRequestMessageH\x00R\x14unpairRequestMessage\x12o\n" +
	"\x15unpairResponseMessage\x18\x04 \x01(\v27.org.derecalliance.derec.protobuf.UnpairResponseMessageH\x00R\x15unpairResponseMessage\x12x\n" +
	"\x18storeShareRequestMessage\x18\x05 \x01(\v2:.org.derecalliance.derec.protobuf.StoreShareRequestMessageH\x00R\x18storeShareRequestMessage\x12{\n" +
	"\x19storeShareResponseMessage\x18\x06 \x01(\v2;.org.derecalliance.derec.protobuf.StoreShareResponseMessageH\x00R\x19storeShareResponseMessage\x12{\n" +
	"\x19verifyShareRequestMessage\x18\a \x01(\v2;.org.derecalliance.derec.protobuf.VerifyShareRequestMessageH\x00R\x19verifyShareRequestMessage\x12~\n" +
	"\x1averifyShareResponseMessage\x18\b \x01(\v2<.org.derecalliance.derec.protobuf.VerifyShareResponseMessageH\x00R\x1averifyShareResponseMessage\x12\x96\x01\n" +
	"\"getSecretIdsVersionsRequestMessage\x18\t \x01(\v2D.org.derecalliance.derec.protobuf.GetSecretIdsVersionsRequestMessageH\x00R\"getSecretIdsVersionsRequestMessage\x12\x99\x01\n" +
	"#getSecretIdsVersionsResponseMessage\x18\n" +
	" \x01(\v2E.org.derecalliance.derec.protobuf.GetSecretIdsVersionsResponseMessageH\x00R#getSecretIdsVersionsResponseMessage\x12r\n" +
	"\x16getShareRequestMessage\x18\v \x01(\v28.org.derecalliance.derec.protobuf.GetShareRequestMessageH\x00R\x16getShareRequestMessage\x12u\n" +
	"\x17getShareResponseMessage\x18\f \x01(\v29.org.derecalliance.derec.protobuf.GetShareResponseMessageH\x00R\x17getShareResponseMessage\x12l\n" +
	"\x14errorResponseMessage\x18\r \x01(\v26.org.derecalliance.derec.protobuf.ErrorResponseMessageH\x00R\x14errorResponseMessage\x12\x8d\x01\n" +
	"\x1fupdateChannelInfoRequestMessage\x18\x0e \x01(\v2A.org.derecalliance.derec.protobuf.UpdateChannelInfoRequestMessageH\x00R\x1fupdateChannelInfoRequestMessage\x12\x90\x01\n" +
	" updateChannelInfoResponseMessage\x18\x0f \x01(\v2B.org.derecalliance.derec.protobuf.UpdateChannelInfoResponseMessageH\x00R updateChannelInfoResponseMessage\x12o\n" +
	"\x15prePairRequestMessage\x18\x10 \x01(\v27.org.derecalliance.derec.protobuf.PrePairRequestMessageH\x00R\x15prePairRequestMessage\x12r\n" +
	"\x16prePairResponseMessage\x18\x11 \x01(\v28.org.derecalliance.derec.protobuf.PrePairResponseMessageH\x00R\x16prePairResponseMessageB\x06\n" +
	"\x04bodyb\x06proto3"

var (
	file_derecmessage_proto_rawDescOnce sync.Once
	file_derecmessage_proto_rawDescData []byte
)

func file_derecmessage_proto_rawDescGZIP() []byte {
	file_derecmessage_proto_rawDescOnce.Do(func() {
		file_derecmessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_derecmessage_proto_rawDesc), len(file_derecmessage_proto_rawDesc)))
	})
	return file_derecmessage_proto_rawDescData
}

var file_derecmessage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_derecmessage_proto_goTypes = []any{
	(*DeRecMessage)(nil),                        // 0: org.derecalliance.derec.protobuf.DeRecMessage
	(*DeRecMessage_MessageBody)(nil),            // 1: org.derecalliance.derec.protobuf.DeRecMessage.MessageBody
	(*timestamppb.Timestamp)(nil),               // 2: google.protobuf.Timestamp
	(*PairRequestMessage)(nil),                  // 3: org.derecalliance.derec.protobuf.PairRequestMessage
	(*PairResponseMessage)(nil),                 // 4: org.derecalliance.derec.protobuf.PairResponseMessage
	(*UnpairRequestMessage)(nil),                // 5: org.derecalliance.derec.protobuf.UnpairRequestMessage
	(*UnpairResponseMessage)(nil),               // 6: org.derecalliance.derec.protobuf.UnpairResponseMessage
	(*StoreShareRequestMessage)(nil),            // 7: org.derecalliance.derec.protobuf.StoreShareRequestMessage
	(*StoreShareResponseMessage)(nil),           // 8: org.derecalliance.derec.protobuf.StoreShareResponseMessage
	(*VerifyShareRequestMessage)(nil),           // 9: org.derecalliance.derec.protobuf.VerifyShareRequestMessage
	(*VerifyShareResponseMessage)(nil),          // 10: org.derecalliance.derec.protobuf.VerifyShareResponseMessage
	(*GetSecretIdsVersionsRequestMessage)(nil),  // 11: org.derecalliance.derec.protobuf.GetSecretIdsVersionsRequestMessage
	(*GetSecretIdsVersionsResponseMessage)(nil), // 12: org.derecalliance.derec.protobuf.GetSecretIdsVersionsResponseMessage
	(*GetShareRequestMessage)(nil),              // 13: org.derecalliance.derec.protobuf.GetShareRequestMessage
	(*GetShareResponseMessage)(nil),             // 14: org.derecalliance.derec.protobuf.GetShareResponseMessage
	(*ErrorResponseMessage)(nil),                // 15: org.derecalliance.derec.protobuf.ErrorResponseMessage
	(*UpdateChannelInfoRequestMessage)(nil),     // 16: org.derecalliance.derec.protobuf.UpdateChannelInfoRequestMessage
	(*UpdateChannelInfoResponseMessage)(nil),    // 17: org.derecalliance.derec.protobuf.UpdateChannelInfoResponseMessage
	(*PrePairRequestMessage)(nil),               // 18: org.derecalliance.derec.protobuf.PrePairRequestMessage
	(*PrePairResponseMessage)(nil),              // 19: org.derecalliance.derec.protobuf.PrePairResponseMessage
}
var file_derecmessage_proto_depIdxs = []int32{
	2,  // 0: org.derecalliance.derec.protobuf.DeRecMessage.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 1: org.derecalliance.derec.protobuf.DeRecMessage.MessageBody.pairRequestMessage:type_name -> org.derecalliance.derec.protobuf.PairRequestMessage
	4,  // 2: org.derecalliance.derec.protobuf.DeRecMessage.MessageBody.pairResponseMessage:type_name -> org.derecalliance.derec.protobuf.PairResponseMessage
	5,  // 3: org.derecalliance.derec.protobuf.DeRecMessage.MessageBody.unpairRequestMessage:type_name -> org.derecalliance.derec.protobuf.UnpairRequestMessage
	6,  // 4: org.derecalliance.derec.protobuf.DeRecMessage.MessageBody.unpairResponseMessage:type_name -> org.derecalliance.derec.protobuf.UnpairResponseMessage
	7,  // 5: org.derecalliance.derec.protobuf.DeRecMessage.MessageBody.storeShareRequestMessage:type_name -> org.derecalliance.derec.protobuf.StoreShareRequestMessage
	8,  // 6: org.derecalliance.derec.protobuf.DeRecMessage.MessageBody.storeShareResponseMessage:type_name -> org.derecalliance.derec.protobuf.StoreShareResponseMessage
	9,  // 7: org.derecalliance.derec.protobuf.DeRecMessage.MessageBody.verifyShareRequestMessage:type_name -> org.derecalliance.derec.protobuf.VerifyShareRequestMessage
	10, // 8: org.derecalliance.derec.protobuf.DeRecMessage.MessageBody.verifyShareResponseMessage:type_name -> org.derecalliance.derec.protobuf.VerifyShareResponseMessage
	11, // 9: org.derecalliance.derec.protobuf.DeRecMessage.MessageBody.getSecretIdsVersionsRequestMessage:type_name -> org.derecalliance.derec.protobuf.GetSecretIdsVersionsRequestMessage
	12, // 10: org.derecalliance.derec.protobuf.DeRecMessage.MessageBody.getSecretIdsVersionsResponseMessage:type_name -> org.derecalliance.derec.protobuf.GetSecretIdsVersionsResponseMessage
	13, // 11: org.derecalliance.derec.protobuf.DeRecMessage.MessageBody.getShareRequestMessage:type_name -> org.derecalliance.derec.protobuf.GetShareRequestMessage
	14, // 12: org.derecalliance.derec.protobuf.DeRecMessage.MessageBody.getShareResponseMessage:type_name -> org.derecalliance.derec.protobuf.GetShareResponseMessage
	15, // 13: org.derecalliance.derec.protobuf.DeRecMessage.MessageBody.errorResponseMessage:type_name -> org.derecalliance.derec.protobuf.ErrorResponseMessage
	16, // 14: org.derecalliance.derec.protobuf.DeRecMessage.MessageBody.updateChannelInfoRequestMessage:type_name -> org.derecalliance.derec.protobuf.UpdateChannelInfoRequestMessage
	17, // 15: org.derecalliance.derec.protobuf.DeRecMessage.MessageBody.updateChannelInfoResponseMessage:type_name -> org.derecalliance.derec.protobuf.UpdateChannelInfoResponseMessage
	18, // 16: org.derecalliance.derec.protobuf.DeRecMessage.MessageBody.prePairRequestMessage:type_name -> org.derecalliance.derec.protobuf.PrePairRequestMessage
	19, // 17: org.derecalliance.derec.protobuf.DeRecMessage.MessageBody.prePairResponseMessage:type_name -> org.derecalliance.derec.protobuf.PrePairResponseMessage
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_derecmessage_proto_init() }
func file_derecmessage_proto_init() {
	if File_derecmessage_proto != nil {
		return
	}
	file_pair_proto_init()
	file_unpair_proto_init()
	file_storeshare_proto_init()
	file_verify_proto_init()
	file_getshare_proto_init()
	file_secretidsversions_proto_init()
	file_updatechannelinfo_proto_init()
	file_prepair_proto_init()
	file_error_proto_init()
	file_derecmessage_proto_msgTypes[1].OneofWrappers = []any{
		(*DeRecMessage_MessageBody_PairRequestMessage)(nil),
		(*DeRecMessage_MessageBody_PairResponseMessage)(nil),
		(*DeRecMessage_MessageBody_UnpairRequestMessage)(nil),
		(*DeRecMessage_MessageBody_UnpairResponseMessage)(nil),
		(*DeRecMessage_MessageBody_StoreShareRequestMessage)(nil),
		(*DeRecMessage_MessageBody_StoreShareResponseMessage)(nil),
		(*DeRecMessage_MessageBody_VerifyShareRequestMessage)(nil),
		(*DeRecMessage_MessageBody_VerifyShareResponseMessage)(nil),
		(*DeRecMessage_MessageBody_GetSecretIdsVersionsRequestMessage)(nil),
		(*DeRecMessage_MessageBody_GetSecretIdsVersionsResponseMessage)(nil),
		(*DeRecMessage_MessageBody_GetShareRequestMessage)(nil),
		(*DeRecMessage_MessageBody_GetShareResponseMessage)(nil),
		(*DeRecMessage_MessageBody_ErrorResponseMessage)(nil),
		(*DeRecMessage_MessageBody_UpdateChannelInfoRequestMessage)(nil),
		(*DeRecMessage_MessageBody_UpdateChannelInfoResponseMessage)(nil),
		(*DeRecMessage_MessageBody_PrePairRequestMessage)(nil),
		(*DeRecMessage_MessageBody_PrePairResponseMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_derecmessage_proto_rawDesc), len(file_derecmessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_derecmessage_proto_goTypes,
		DependencyIndexes: file_derecmessage_proto_depIdxs,
		MessageInfos:      file_derecmessage_proto_msgTypes,
	}.Build()
	File_derecmessage_proto = out.File
	file_derecmessage_proto_goTypes = nil
	file_derecmessage_proto_depIdxs = nil
}
