//
// Copyright (c) DeRec Alliance and its Contributors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: derecsecret.proto

package derecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HelperSpecificInfo captures per-helper metadata associated with a secret.
//
// # Purpose
//
// This message binds a specific Helper to:
//
// - its identity (via a hash of its public encryption key)
// - the parameters agreed during pairing with the Owner
//
// This information allows the Owner to:
//
// - track which Helpers are associated with a given secret
// - reconstruct the correct configuration during recovery
// - verify that Helpers are operating under the expected parameters
//
// # Semantics
//
// Each entry represents one Helper participating in the secret sharing
// scheme. The collection of these entries defines the Helper set for
// a given version of the secret.
//
// # Identity Binding
//
// The `helper` field is a SHA-384 hash of the Helper's public encryption
// key. This provides a stable identifier without exposing the key itself.
//
// Implementations MUST ensure that:
//
// - the hash corresponds to the exact public key used during pairing
// - the mapping between Helper identity and key is preserved
//
// # Parameter Agreement
//
// The `helperParams` field records the parameter range agreed between
// the Owner and the Helper during pairing. This ensures that:
//
// - the share distribution is consistent with negotiated constraints
// - recovery can validate expected parameters
type HelperSpecificInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SHA-384 hash of the Helper's public encryption key.
	//
	// This uniquely identifies the Helper within the context of the secret
	// without exposing the raw key material.
	Helper []byte `protobuf:"bytes,1,opt,name=helper,proto3" json:"helper,omitempty"`
	// Parameters agreed upon between the Helper and the Owner.
	//
	// These parameters originate from the intersection of both parties'
	// supported ranges during pairing.
	HelperParams  *ParameterRange `protobuf:"bytes,2,opt,name=helperParams,proto3" json:"helperParams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelperSpecificInfo) Reset() {
	*x = HelperSpecificInfo{}
	mi := &file_derecsecret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelperSpecificInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelperSpecificInfo) ProtoMessage() {}

func (x *HelperSpecificInfo) ProtoReflect() protoreflect.Message {
	mi := &file_derecsecret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelperSpecificInfo.ProtoReflect.Descriptor instead.
func (*HelperSpecificInfo) Descriptor() ([]byte, []int) {
	return file_derecsecret_proto_rawDescGZIP(), []int{0}
}

func (x *HelperSpecificInfo) GetHelper() []byte {
	if x != nil {
		return x.Helper
	}
	return nil
}

func (x *HelperSpecificInfo) GetHelperParams() *ParameterRange {
	if x != nil {
		return x.HelperParams
	}
	return nil
}

// DeRecSecret represents the canonical structure of the secret material
// that is encrypted and distributed across Helpers.
//
// # Context
//
// Before distribution:
//
// - the Owner constructs a DeRecSecret
// - the `secretData` is encrypted (e.g., via AES-GCM)
// - the encryption key is split using a secret sharing scheme (e.g., Shamir)
//
// The resulting shares are then distributed to Helpers.
//
// This message defines the structure used by "share algorithm 0".
//
// # Semantics
//
// A DeRecSecret contains:
//
// - the raw secret payload
// - metadata describing the sharing configuration
// - the set of Helpers and their associated parameters
//
// This metadata is critical for:
//
// - reconstructing the secret during recovery
// - validating the integrity and configuration of shares
//
// # Thresholds
//
// Two thresholds are defined:
//
// 1. Recovery threshold:
//   - Minimum number of Helpers required to reconstruct the secret
//
// 2. Confirmation threshold:
//   - Minimum number of Helpers that must acknowledge receipt of a new
//     share version before older versions can be safely deleted
//
// # Security Considerations
//
// - The entire DeRecSecret MUST be encrypted before distribution
// - Helpers MUST NOT have access to the plaintext secretData
// - Metadata should not leak sensitive information beyond what is required
//
// # Versioning
//
// Each share distribution version implicitly corresponds to a snapshot
// of this structure. Changes to:
//
// - secretData
// - helper set
// - thresholds
//
// result in a new version being generated and distributed.
type DeRecSecret struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Arbitrary secret payload.
	//
	// This may include cryptographic keys, credentials, documents, or any
	// serialized data the Owner wishes to protect. When produced by the DeRec
	// library, these bytes are the recoverable secret: a 1-byte version prefix
	// followed by a versioned payload (v1 = gzip-compressed (RFC 1952) JSON,
	// base64 (RFC 4648 §4) byte fields, u64 as decimal strings). Other payloads
	// MAY use a different encoding; secretData is opaque to the protocol.
	SecretData []byte `protobuf:"bytes,1,opt,name=secretData,proto3" json:"secretData,omitempty"`
	// Timestamp indicating when this secret (or this version of it) was created.
	//
	// Used for auditing, version tracking, and observability.
	CreationTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=creationTime,proto3" json:"creationTime,omitempty"`
	// Minimum number of Helpers required to reconstruct the secret.
	//
	// This corresponds to the threshold parameter of the underlying
	// secret sharing scheme.
	HelperThresholdForRecovery int64 `protobuf:"varint,3,opt,name=helperThresholdForRecovery,proto3" json:"helperThresholdForRecovery,omitempty"`
	// Minimum number of Helpers that must confirm receipt of a share
	// before older versions can be deleted.
	//
	// This ensures that sufficient redundancy exists before removing
	// previous share versions.
	HelperThresholdForConfirmingShareReceipt int64 `protobuf:"varint,4,opt,name=helperThresholdForConfirmingShareReceipt,proto3" json:"helperThresholdForConfirmingShareReceipt,omitempty"`
	// List of Helpers participating in this secret.
	//
	// Each entry defines:
	//
	// - the identity of the Helper
	// - the parameters agreed with that Helper
	//
	// The size of this list defines the total number of shares generated.
	Helpers       []*HelperSpecificInfo `protobuf:"bytes,5,rep,name=helpers,proto3" json:"helpers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeRecSecret) Reset() {
	*x = DeRecSecret{}
	mi := &file_derecsecret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeRecSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeRecSecret) ProtoMessage() {}

func (x *DeRecSecret) ProtoReflect() protoreflect.Message {
	mi := &file_derecsecret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeRecSecret.ProtoReflect.Descriptor instead.
func (*DeRecSecret) Descriptor() ([]byte, []int) {
	return file_derecsecret_proto_rawDescGZIP(), []int{1}
}

func (x *DeRecSecret) GetSecretData() []byte {
	if x != nil {
		return x.SecretData
	}
	return nil
}

func (x *DeRecSecret) GetCreationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

func (x *DeRecSecret) GetHelperThresholdForRecovery() int64 {
	if x != nil {
		return x.HelperThresholdForRecovery
	}
	return 0
}

func (x *DeRecSecret) GetHelperThresholdForConfirmingShareReceipt() int64 {
	if x != nil {
		return x.HelperThresholdForConfirmingShareReceipt
	}
	return 0
}

func (x *DeRecSecret) GetHelpers() []*HelperSpecificInfo {
	if x != nil {
		return x.Helpers
	}
	return nil
}

var File_derecsecret_proto protoreflect.FileDescriptor

const file_derecsecret_proto_rawDesc = "" +
	"\n" +
	"\x11derecsecret.proto\x12 org.derecalliance.derec.protobuf\x1a\fresult.proto\x1a\x14parameterrange.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x01\n" +
	"\x12HelperSpecificInfo\x12\x16\n" +
	"\x06helper\x18\x01 \x01(\fR\x06helper\x12T\n" +
	"\fhelperParams\x18\x02 \x01(\v20.org.derecalliance.derec.protobuf.ParameterRangeR\fhelperParams\"\xd9\x02\n" +
	"\vDeRecSecret\x12\x1e\n" +
	"\n" +
	"secretData\x18\x01 \x01(\fR\n" +
	"secretData\x12>\n" +
	"\fcreationTime\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fcreationTime\x12>\n" +
	"\x1ahelperThresholdForRecovery\x18\x03 \x01(\x03R\x1ahelperThresholdForRecovery\x12Z\n" +
	"(helperThresholdForConfirmingShareReceipt\x18\x04 \x01(\x03R(helperThresholdForConfirmingShareReceipt\x12N\n" +
	"\ahelpers\x18\x05 \x03(\v24.org.derecalliance.derec.protobuf.HelperSpecificInfoR\ahelpersb\x06proto3"

var (
	file_derecsecret_proto_rawDescOnce sync.Once
	file_derecsecret_proto_rawDescData []byte
)

func file_derecsecret_proto_rawDescGZIP() []byte {
	file_derecsecret_proto_rawDescOnce.Do(func() {
		file_derecsecret_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_derecsecret_proto_rawDesc), len(file_derecsecret_proto_rawDesc)))
	})
	return file_derecsecret_proto_rawDescData
}

var file_derecsecret_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_derecsecret_proto_goTypes = []any{
	(*HelperSpecificInfo)(nil),    // 0: org.derecalliance.derec.protobuf.HelperSpecificInfo
	(*DeRecSecret)(nil),           // 1: org.derecalliance.derec.protobuf.DeRecSecret
	(*ParameterRange)(nil),        // 2: org.derecalliance.derec.protobuf.ParameterRange
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_derecsecret_proto_depIdxs = []int32{
	2, // 0: org.derecalliance.derec.protobuf.HelperSpecificInfo.helperParams:type_name -> org.derecalliance.derec.protobuf.ParameterRange
	3, // 1: org.derecalliance.derec.protobuf.DeRecSecret.creationTime:type_name -> google.protobuf.Timestamp
	0, // 2: org.derecalliance.derec.protobuf.DeRecSecret.helpers:type_name -> org.derecalliance.derec.protobuf.HelperSpecificInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_derecsecret_proto_init() }
func file_derecsecret_proto_init() {
	if File_derecsecret_proto != nil {
		return
	}
	file_result_proto_init()
	file_parameterrange_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_derecsecret_proto_rawDesc), len(file_derecsecret_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_derecsecret_proto_goTypes,
		DependencyIndexes: file_derecsecret_proto_depIdxs,
		MessageInfos:      file_derecsecret_proto_msgTypes,
	}.Build()
	File_derecsecret_proto = out.File
	file_derecsecret_proto_goTypes = nil
	file_derecsecret_proto_depIdxs = nil
}
