//
// Copyright (c) DeRec Alliance and its Contributors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: derectransport.proto

package derecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_derectransport_proto protoreflect.FileDescriptor

const file_derectransport_proto_rawDesc = "" +
	"\n" +
	"\x14derectransport.proto\x12 org.derecalliance.derec.protobuf\x1a\x12derecmessage.proto\x1a\x1bgoogle/protobuf/empty.proto2`\n" +
	"\x0eDeRecTransport\x12N\n" +
	"\x04Send\x12..org.derecalliance.derec.protobuf.DeRecMessage\x1a\x16.google.protobuf.Emptyb\x06proto3"

var file_derectransport_proto_goTypes = []any{
	(*DeRecMessage)(nil),  // 0: org.derecalliance.derec.protobuf.DeRecMessage
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_derectransport_proto_depIdxs = []int32{
	0, // 0: org.derecalliance.derec.protobuf.DeRecTransport.Send:input_type -> org.derecalliance.derec.protobuf.DeRecMessage
	1, // 1: org.derecalliance.derec.protobuf.DeRecTransport.Send:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_derectransport_proto_init() }
func file_derectransport_proto_init() {
	if File_derectransport_proto != nil {
		return
	}
	file_derecmessage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_derectransport_proto_rawDesc), len(file_derectransport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_derectransport_proto_goTypes,
		DependencyIndexes: file_derectransport_proto_depIdxs,
	}.Build()
	File_derectransport_proto = out.File
	file_derectransport_proto_goTypes = nil
	file_derectransport_proto_depIdxs = nil
}
