//
// Copyright (c) DeRec Alliance and its Contributors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: error.proto

package derecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorResponseMessage is a generic error response sent when a protocol
// message cannot be processed successfully.
//
// # Context
//
// This message may be returned in response to any DeRecMessage when the
// receiver encounters an error during processing.
//
// Typical scenarios include:
//
// - malformed or invalid message payloads
// - unsupported or unknown message types
// - protocol violations (e.g., invalid sequence, nonce mismatch)
// - authorization or validation failures
//
// # Semantics
//
// This message indicates that:
//
// - the original request was not successfully processed
// - no state change should be assumed by the sender
//
// The sender SHOULD:
//
// - inspect the `result` field to determine the cause of the failure
// - decide whether to retry, abort, or escalate based on the error
//
// # Usage Guidelines
//
//   - This message is intended as a fallback when no more specific response
//     type is applicable
//   - Protocol-specific errors SHOULD use their corresponding response
//     messages when available
//
// # Security Considerations
//
// - Error responses SHOULD avoid leaking sensitive internal details
// - Only high-level error information should be exposed via `result`
//
// # Idempotency
//
// Error responses are idempotent and may be returned multiple times
// for repeated invalid requests.
type ErrorResponseMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result describing the error encountered while processing the request.
	//
	// This field encodes the error type and any associated status information.
	Result        *DeRecResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponseMessage) Reset() {
	*x = ErrorResponseMessage{}
	mi := &file_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponseMessage) ProtoMessage() {}

func (x *ErrorResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponseMessage.ProtoReflect.Descriptor instead.
func (*ErrorResponseMessage) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResponseMessage) GetResult() *DeRecResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_error_proto protoreflect.FileDescriptor

const file_error_proto_rawDesc = "" +
	"\n" +
	"\verror.proto\x12 org.derecalliance.derec.protobuf\x1a\fresult.proto\"]\n" +
	"\x14ErrorResponseMessage\x12E\n" +
	"\x06result\x18\x01 \x01(\v2-.org.derecalliance.derec.protobuf.DeRecResultR\x06resultb\x06proto3"

var (
	file_error_proto_rawDescOnce sync.Once
	file_error_proto_rawDescData []byte
)

func file_error_proto_rawDescGZIP() []byte {
	file_error_proto_rawDescOnce.Do(func() {
		file_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_error_proto_rawDesc), len(file_error_proto_rawDesc)))
	})
	return file_error_proto_rawDescData
}

var file_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_error_proto_goTypes = []any{
	(*ErrorResponseMessage)(nil), // 0: org.derecalliance.derec.protobuf.ErrorResponseMessage
	(*DeRecResult)(nil),          // 1: org.derecalliance.derec.protobuf.DeRecResult
}
var file_error_proto_depIdxs = []int32{
	1, // 0: org.derecalliance.derec.protobuf.ErrorResponseMessage.result:type_name -> org.derecalliance.derec.protobuf.DeRecResult
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_error_proto_init() }
func file_error_proto_init() {
	if File_error_proto != nil {
		return
	}
	file_result_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_error_proto_rawDesc), len(file_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_proto_goTypes,
		DependencyIndexes: file_error_proto_depIdxs,
		MessageInfos:      file_error_proto_msgTypes,
	}.Build()
	File_error_proto = out.File
	file_error_proto_goTypes = nil
	file_error_proto_depIdxs = nil
}
