//
// Copyright (c) DeRec Alliance and its Contributors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: getshare.proto

package derecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetShareRequestMessage requests a previously stored share from a Helper.
//
// # Context
//
// This message is used during the recovery flow, after pairing has been
// established (typically in recovery mode). Once a Helper has indicated
// which secret IDs and versions it holds, the Owner sends this request
// to retrieve specific shares.
//
// # Semantics
//
// The request identifies a share by:
//
// - `secretId`: the identifier of the protected secret
// - `version`: the version of the share distribution
//
// The Helper is expected to locate the corresponding share and return it
// in a GetShareResponseMessage.
//
// # Authorization Rules
//
// The Helper MUST only process this request if it is received through a
// valid communication channel that is authorized to access the requested
// share. Specifically:
//
//   - the request MUST originate from the same secretId channel, OR
//   - the request MUST originate from a channel established in recovery mode
//     and associated with the same user
//
// Otherwise, the Helper MUST reject the request.
//
// # Idempotency
//
// This request is idempotent. Repeated requests for the same (secretId,
// version) pair SHOULD return the same result.
type GetShareRequestMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Numeric identifier of the secret for which the share is requested.
	//
	// Generated by the Owner when the secret is created. It uniquely
	// identifies the secret within the context of the Owner and its Helpers.
	SecretId uint64 `protobuf:"varint,1,opt,name=secretId,proto3" json:"secretId,omitempty"`
	// Version of the share being requested.
	//
	// Each time a secret is reshared (e.g., due to updates or changes in
	// helper set), a new version is created. This field specifies which
	// version of the share should be returned.
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// Timestamp indicating when this message was created.
	//
	// This value is expressed in UTC and can be used for:
	//
	// - observability and logging
	// - replay detection (in combination with sequence numbers)
	// - timeout handling
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Ephemeral transport endpoint at which the requester wants to receive
	// the response to *this exchange*, overriding the channel's stored peer
	// endpoint for this round-trip only.
	//
	// See `StoreShareRequestMessage.replyTo` for full semantics. Empty =
	// route to the stored channel endpoint; Present = route this response
	// here without persisting the endpoint.
	ReplyTo []*TransportProtocol `protobuf:"bytes,4,rep,name=replyTo,proto3" json:"replyTo,omitempty"`
	// Identity of the replica-group member this message concerns.
	//
	// Present **only** on the replica path, where a member drives catch-up
	// against another member. Absent on the owner ↔ helper path, which is
	// unchanged.
	//
	// Every member of a group is addressed on one shared `channel_id`, so the
	// channel cannot name the peer — this field does. Its presence is also what
	// tells the receiver which path a message belongs to.
	ReplicaId     *uint64 `protobuf:"varint,5,opt,name=replicaId,proto3,oneof" json:"replicaId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareRequestMessage) Reset() {
	*x = GetShareRequestMessage{}
	mi := &file_getshare_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareRequestMessage) ProtoMessage() {}

func (x *GetShareRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_getshare_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareRequestMessage.ProtoReflect.Descriptor instead.
func (*GetShareRequestMessage) Descriptor() ([]byte, []int) {
	return file_getshare_proto_rawDescGZIP(), []int{0}
}

func (x *GetShareRequestMessage) GetSecretId() uint64 {
	if x != nil {
		return x.SecretId
	}
	return 0
}

func (x *GetShareRequestMessage) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetShareRequestMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GetShareRequestMessage) GetReplyTo() []*TransportProtocol {
	if x != nil {
		return x.ReplyTo
	}
	return nil
}

func (x *GetShareRequestMessage) GetReplicaId() uint64 {
	if x != nil && x.ReplicaId != nil {
		return *x.ReplicaId
	}
	return 0
}

// GetShareResponseMessage returns a share previously stored by the Helper.
//
// # Semantics
//
// This message is sent in response to a GetShareRequestMessage. It either:
//
// - returns the requested share (on success), or
// - indicates failure via the `result` field
//
// # Authorization Enforcement
//
// The Helper MUST ensure that the request satisfies the authorization rules
// described in GetShareRequestMessage before returning any share data.
//
// # Share Contents
//
// The returned share is an opaque byte sequence that typically includes:
//
// - the Shamir share (x, y)
// - the encrypted secret payload (or a reference to it)
// - the commitment (e.g., Merkle root)
// - the opening proof for verification
//
// The exact structure is defined by the share algorithm indicated in
// `shareAlgorithm`.
//
// # Security Considerations
//
//   - The share MUST only be returned over an authenticated and encrypted
//     DeRec channel
//   - Incorrect or malicious shares may be detected by the Owner during
//     recovery using commitment verification
//
// # Idempotency
//
// For a given (secretId, version), repeated responses SHOULD return
// the same share data.
type GetShareResponseMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result of processing the request.
	//
	// Indicates whether the share was successfully retrieved or if an error
	// occurred (e.g., unauthorized request, unknown secretId, or missing version).
	Result *DeRecResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// The committed DeRec share.
	//
	// This is an opaque byte array containing the share data as produced by
	// the share distribution algorithm. Its internal structure depends on
	// `shareAlgorithm`.
	CommittedDeRecShare []byte `protobuf:"bytes,2,opt,name=committedDeRecShare,proto3" json:"committedDeRecShare,omitempty"`
	// Identifier of the share algorithm used to produce the share.
	//
	// This allows the recipient to interpret and process the share correctly
	// during verification and reconstruction.
	ShareAlgorithm int32 `protobuf:"varint,3,opt,name=shareAlgorithm,proto3" json:"shareAlgorithm,omitempty"`
	// Timestamp indicating when this message was created.
	//
	// This value is expressed in UTC and can be used for observability,
	// replay detection, and timeout handling.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Identifier of the secret to which this response refers.
	//
	// Echoed from the corresponding GetShareRequestMessage so the Owner can
	// correlate responses with the correct pending recovery without inspecting
	// the share bytes. Required when the Owner has multiple recoveries in
	// progress concurrently, or to defend against stale responses from a
	// previously-abandoned recovery attempt.
	SecretId uint64 `protobuf:"varint,5,opt,name=secretId,proto3" json:"secretId,omitempty"`
	// Version of the share being returned.
	//
	// Echoed from the corresponding GetShareRequestMessage for the same
	// correlation reasons as `secretId`.
	Version uint32 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	// Identity of the replica-group member this message concerns.
	//
	// Present **only** on the replica path, where a member drives catch-up
	// against another member. Absent on the owner ↔ helper path, which is
	// unchanged.
	//
	// Every member of a group is addressed on one shared `channel_id`, so the
	// channel cannot name the peer — this field does. Its presence is also what
	// tells the receiver which path a message belongs to.
	ReplicaId     *uint64 `protobuf:"varint,7,opt,name=replicaId,proto3,oneof" json:"replicaId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareResponseMessage) Reset() {
	*x = GetShareResponseMessage{}
	mi := &file_getshare_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareResponseMessage) ProtoMessage() {}

func (x *GetShareResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_getshare_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareResponseMessage.ProtoReflect.Descriptor instead.
func (*GetShareResponseMessage) Descriptor() ([]byte, []int) {
	return file_getshare_proto_rawDescGZIP(), []int{1}
}

func (x *GetShareResponseMessage) GetResult() *DeRecResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetShareResponseMessage) GetCommittedDeRecShare() []byte {
	if x != nil {
		return x.CommittedDeRecShare
	}
	return nil
}

func (x *GetShareResponseMessage) GetShareAlgorithm() int32 {
	if x != nil {
		return x.ShareAlgorithm
	}
	return 0
}

func (x *GetShareResponseMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GetShareResponseMessage) GetSecretId() uint64 {
	if x != nil {
		return x.SecretId
	}
	return 0
}

func (x *GetShareResponseMessage) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetShareResponseMessage) GetReplicaId() uint64 {
	if x != nil && x.ReplicaId != nil {
		return *x.ReplicaId
	}
	return 0
}

var File_getshare_proto protoreflect.FileDescriptor

const file_getshare_proto_rawDesc = "" +
	"\n" +
	"\x0egetshare.proto\x12 org.derecalliance.derec.protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fresult.proto\x1a\x17transportprotocol.proto\"\x88\x02\n" +
	"\x16GetShareRequestMessage\x12\x1a\n" +
	"\bsecretId\x18\x01 \x01(\x04R\bsecretId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12M\n" +
	"\areplyTo\x18\x04 \x03(\v23.org.derecalliance.derec.protobuf.TransportProtocolR\areplyTo\x12!\n" +
	"\treplicaId\x18\x05 \x01(\x04H\x00R\treplicaId\x88\x01\x01B\f\n" +
	"\n" +
	"_replicaId\"\xdb\x02\n" +
	"\x17GetShareResponseMessage\x12E\n" +
	"\x06result\x18\x01 \x01(\v2-.org.derecalliance.derec.protobuf.DeRecResultR\x06result\x120\n" +
	"\x13committedDeRecShare\x18\x02 \x01(\fR\x13committedDeRecShare\x12&\n" +
	"\x0eshareAlgorithm\x18\x03 \x01(\x05R\x0eshareAlgorithm\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1a\n" +
	"\bsecretId\x18\x05 \x01(\x04R\bsecretId\x12\x18\n" +
	"\aversion\x18\x06 \x01(\rR\aversion\x12!\n" +
	"\treplicaId\x18\a \x01(\x04H\x00R\treplicaId\x88\x01\x01B\f\n" +
	"\n" +
	"_replicaIdb\x06proto3"

var (
	file_getshare_proto_rawDescOnce sync.Once
	file_getshare_proto_rawDescData []byte
)

func file_getshare_proto_rawDescGZIP() []byte {
	file_getshare_proto_rawDescOnce.Do(func() {
		file_getshare_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_getshare_proto_rawDesc), len(file_getshare_proto_rawDesc)))
	})
	return file_getshare_proto_rawDescData
}

var file_getshare_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_getshare_proto_goTypes = []any{
	(*GetShareRequestMessage)(nil),  // 0: org.derecalliance.derec.protobuf.GetShareRequestMessage
	(*GetShareResponseMessage)(nil), // 1: org.derecalliance.derec.protobuf.GetShareResponseMessage
	(*timestamppb.Timestamp)(nil),   // 2: google.protobuf.Timestamp
	(*TransportProtocol)(nil),       // 3: org.derecalliance.derec.protobuf.TransportProtocol
	(*DeRecResult)(nil),             // 4: org.derecalliance.derec.protobuf.DeRecResult
}
var file_getshare_proto_depIdxs = []int32{
	2, // 0: org.derecalliance.derec.protobuf.GetShareRequestMessage.timestamp:type_name -> google.protobuf.Timestamp
	3, // 1: org.derecalliance.derec.protobuf.GetShareRequestMessage.replyTo:type_name -> org.derecalliance.derec.protobuf.TransportProtocol
	4, // 2: org.derecalliance.derec.protobuf.GetShareResponseMessage.result:type_name -> org.derecalliance.derec.protobuf.DeRecResult
	2, // 3: org.derecalliance.derec.protobuf.GetShareResponseMessage.timestamp:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_getshare_proto_init() }
func file_getshare_proto_init() {
	if File_getshare_proto != nil {
		return
	}
	file_result_proto_init()
	file_transportprotocol_proto_init()
	file_getshare_proto_msgTypes[0].OneofWrappers = []any{}
	file_getshare_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_getshare_proto_rawDesc), len(file_getshare_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_getshare_proto_goTypes,
		DependencyIndexes: file_getshare_proto_depIdxs,
		MessageInfos:      file_getshare_proto_msgTypes,
	}.Build()
	File_getshare_proto = out.File
	file_getshare_proto_goTypes = nil
	file_getshare_proto_depIdxs = nil
}
