//
// Copyright (c) DeRec Alliance and its Contributors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pair.proto

package derecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SenderKind identifies the logical role of the sender in the pairing flow.
//
// The role determines how the receiver interprets the message and what
// role each party takes in the resulting channel. Pairs are formed by
// matching complementary kinds: Owner↔Helper, ReplicaSource↔ReplicaDestination.
type SenderKind int32

const (
	// Sender is an Owner.
	//
	// Used for all Owner-initiated pairings, whether establishing a new
	// relationship or re-pairing during recovery. There is no protocol-level
	// distinction between the two cases.
	SenderKind_OWNER SenderKind = 0
	// Sender is acting as a Helper.
	//
	// Helpers may initiate pairing in some application flows, though the
	// Owner typically acts as the initiator.
	SenderKind_HELPER SenderKind = 1
	// Sender is the Source side of a replica pair — the device that owns
	// the secrets and pushes them to a destination for backup. The matching
	// peer kind is REPLICA_DESTINATION.
	//
	// Replica pairing follows the same cryptographic handshake as Helper
	// pairing but adds a mandatory fingerprint-verify step before the
	// channel transitions out of `Pending`. After verification, the Source
	// calls ProtectSecret targeting the Destination channel; the library
	// sends a `ReplicaSecretPayload` (full secret + share map) to the
	// Destination via a normal channel-mode `StoreShareRequest`.
	SenderKind_REPLICA_SOURCE SenderKind = 3
	// Sender is the Destination side of a replica pair — the device that
	// receives and stores full secret copies from a Source for backup or
	// recovery purposes. The matching peer kind is REPLICA_SOURCE.
	//
	// The Destination never initiates ProtectSecret on this channel; it
	// only receives `ReplicaSecretPayload` messages and surfaces them to
	// the application via the `ReplicaSecretReceived` event.
	SenderKind_REPLICA_DESTINATION SenderKind = 4
)

// Enum value maps for SenderKind.
var (
	SenderKind_name = map[int32]string{
		0: "OWNER",
		1: "HELPER",
		3: "REPLICA_SOURCE",
		4: "REPLICA_DESTINATION",
	}
	SenderKind_value = map[string]int32{
		"OWNER":               0,
		"HELPER":              1,
		"REPLICA_SOURCE":      3,
		"REPLICA_DESTINATION": 4,
	}
)

func (x SenderKind) Enum() *SenderKind {
	p := new(SenderKind)
	*p = x
	return p
}

func (x SenderKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SenderKind) Descriptor() protoreflect.EnumDescriptor {
	return file_pair_proto_enumTypes[0].Descriptor()
}

func (SenderKind) Type() protoreflect.EnumType {
	return &file_pair_proto_enumTypes[0]
}

func (x SenderKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SenderKind.Descriptor instead.
func (SenderKind) EnumDescriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{0}
}

// PairRequestMessage is the first message in the pairing protocol,
// sent from the initiator to the responder after receiving a ContactMessage.
//
// # Preconditions
//
// Before sending this message:
//
//   - The initiator MUST have received a valid ContactMessage from the responder
//   - The initiator MUST use the responder's public encryption material from
//     the ContactMessage to construct this request
//
// # Purpose
//
// This message establishes:
//
// - the initiator's identity and role (Owner/Helper, recovery mode or not)
// - fresh cryptographic material for the responder to use in subsequent messages
// - agreement negotiation inputs (parameter ranges)
// - binding between the out-of-band contact exchange and this pairing attempt
// - transport information for future communication
//
// # Security Properties
//
// - The nonce binds this request to the ContactMessage exchange
// - The ciphertext and public keys bootstrap a secure communication channel
// - The message is encrypted and authenticated at the DeRecMessage layer
//
// # Outcome
//
// Upon successful processing, the responder replies with PairResponseMessage.
// After this exchange:
//
// - both parties know each other's public keys
// - a secure communication channel is established for subsequent protocol flows
type PairRequestMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The role of the sender of this message.
	//
	// This informs the responder whether the initiator is:
	//
	// - an Owner (normal or recovery mode), or
	// - a Helper
	//
	// Recovery mode has special semantics for how Helpers associate this
	// pairing with existing stored secrets.
	SenderKind SenderKind `protobuf:"varint,1,opt,name=senderKind,proto3,enum=org.derecalliance.derec.protobuf.SenderKind" json:"senderKind,omitempty"`
	// ML-KEM-768 ciphertext.
	//
	// This ciphertext is generated using the responder's ML-KEM public key
	// obtained from the ContactMessage. It is used to establish shared
	// cryptographic material for securing subsequent communication.
	MlkemCiphertext []byte `protobuf:"bytes,2,opt,name=mlkemCiphertext,proto3" json:"mlkemCiphertext,omitempty"`
	// Serialized ECIES public key of the sender.
	//
	// This key is provided to the responder so that future messages can be
	// encrypted toward the initiator.
	EciesPublicKey []byte `protobuf:"bytes,3,opt,name=eciesPublicKey,proto3" json:"eciesPublicKey,omitempty"`
	// Sender's application-level identifying information.
	//
	// This field is intended for user-facing identification and may include
	// data such as name, phone number, or account identifiers.
	//
	// It is not used directly by the protocol for security decisions.
	CommunicationInfo *CommunicationInfo `protobuf:"bytes,5,opt,name=communicationInfo,proto3" json:"communicationInfo,omitempty"`
	// Nonce binding this request to the ContactMessage exchange.
	//
	// This value MUST match the nonce provided in the ContactMessage.
	// It allows the responder to verify that the pairing request corresponds
	// to the same out-of-band interaction, preventing mismatched or spoofed
	// pairing attempts.
	Nonce uint64 `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Parameter range supported by the sender.
	//
	// This defines the acceptable configuration space (e.g., thresholds,
	// limits) that the sender is willing to operate under.
	//
	// The responder combines this with its own parameter range to determine
	// whether pairing is possible and which parameters to use.
	ParameterRange *ParameterRange `protobuf:"bytes,7,opt,name=parameterRange,proto3" json:"parameterRange,omitempty"`
	// Transport information for reaching the initiator.
	//
	// This specifies:
	//
	// - the endpoint where the initiator can receive messages
	// - the protocol required to deliver those messages
	//
	// After pairing, the responder uses this information to send responses
	// and all subsequent protocol messages to the initiator.
	TransportProtocol *TransportProtocol `protobuf:"bytes,8,opt,name=transportProtocol,proto3" json:"transportProtocol,omitempty"`
	// Timestamp indicating when this message was created.
	//
	// Used for observability and may assist in replay detection or timeout
	// handling, depending on the implementation.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairRequestMessage) Reset() {
	*x = PairRequestMessage{}
	mi := &file_pair_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairRequestMessage) ProtoMessage() {}

func (x *PairRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairRequestMessage.ProtoReflect.Descriptor instead.
func (*PairRequestMessage) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{0}
}

func (x *PairRequestMessage) GetSenderKind() SenderKind {
	if x != nil {
		return x.SenderKind
	}
	return SenderKind_OWNER
}

func (x *PairRequestMessage) GetMlkemCiphertext() []byte {
	if x != nil {
		return x.MlkemCiphertext
	}
	return nil
}

func (x *PairRequestMessage) GetEciesPublicKey() []byte {
	if x != nil {
		return x.EciesPublicKey
	}
	return nil
}

func (x *PairRequestMessage) GetCommunicationInfo() *CommunicationInfo {
	if x != nil {
		return x.CommunicationInfo
	}
	return nil
}

func (x *PairRequestMessage) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *PairRequestMessage) GetParameterRange() *ParameterRange {
	if x != nil {
		return x.ParameterRange
	}
	return nil
}

func (x *PairRequestMessage) GetTransportProtocol() *TransportProtocol {
	if x != nil {
		return x.TransportProtocol
	}
	return nil
}

func (x *PairRequestMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// PairResponseMessage is the response to a PairRequestMessage.
//
// # Purpose
//
// This message completes the pairing handshake. It informs the initiator:
//
// - whether the pairing was accepted or rejected
// - the responder's role and identity information
// - the responder's supported parameter range
//
// # Differences from PairRequestMessage
//
//   - Does not include encryption public keys, as those were already exchanged
//     via ContactMessage and PairRequestMessage
//   - Includes a Result field indicating success or failure
//
// # Semantics
//
//   - If `result` indicates success, a secure channel is considered established
//   - If `result` indicates failure, the pairing MUST be treated as unsuccessful
//     and no further protocol messages should be exchanged on this channel
//
// The nonce MUST match the value provided in the request, ensuring that the
// response corresponds to the same pairing session.
type PairResponseMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result of processing the pairing request.
	//
	// Indicates whether the pairing was successful or failed.
	// Failure may occur due to:
	//
	// - incompatible parameter ranges
	// - failed authentication at the application layer
	// - invalid or malformed request data
	Result *DeRecResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// Application-level identifying information of the responder.
	//
	// Intended for user-facing identification and display purposes.
	CommunicationInfo *CommunicationInfo `protobuf:"bytes,4,opt,name=communicationInfo,proto3" json:"communicationInfo,omitempty"`
	// Nonce identifying the pairing session.
	//
	// This value MUST exactly match the nonce received in the
	// PairRequestMessage. A mismatch indicates an invalid or unrelated
	// pairing attempt and SHOULD result in rejection.
	Nonce uint64 `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Parameter range supported by the responder.
	//
	// The initiator combines this with its own parameter range to determine
	// the final agreed configuration for the channel.
	ParameterRange *ParameterRange `protobuf:"bytes,6,opt,name=parameterRange,proto3" json:"parameterRange,omitempty"`
	// Timestamp indicating when this message was created.
	//
	// Used for observability and may assist in replay detection or timeout
	// handling, depending on the implementation.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Derived channel identifier the two parties switch to immediately after
	// the pairing handshake completes. This message is the only place this
	// value travels on the wire, and it travels encrypted (inside the pairing
	// envelope), so a passive observer who only sees the pre-rekey traffic
	// cannot link the now-paired session to its long-running successor.
	//
	// # Derivation
	//
	// The responder computes:
	//
	// ```text
	// channelId = u64::from_be_bytes(
	//
	//	SHA-384(
	//	    u64_be(originalChannelId) || sharedKeyBytes
	//	)[0..8]
	//
	// )
	// ```
	//
	// where `originalChannelId` is the channelId from the contact / pairing
	// envelopes and `sharedKeyBytes` is the freshly-derived pairing shared
	// key.
	//
	// # Validation
	//
	// The requester MUST recompute the same hash with its own derivation of
	// the shared key and reject the response (closing the would-be channel)
	// if the value here does not match. A non-matching value indicates either
	// a key-derivation mismatch (the channel would be unusable anyway) or
	// tampering by a peer that somehow forged a valid envelope but cannot
	// produce the SHA-384 preimage.
	//
	// # Effect
	//
	// Both parties atomically rekey their local channel record from
	// `originalChannelId` to this value once the handshake is accepted. All
	// subsequent envelopes on this channel — including the
	// UpdateChannelInfo handover for the long-term transport — route on the
	// new id.
	ChannelId     uint64 `protobuf:"varint,8,opt,name=channelId,proto3" json:"channelId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairResponseMessage) Reset() {
	*x = PairResponseMessage{}
	mi := &file_pair_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairResponseMessage) ProtoMessage() {}

func (x *PairResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairResponseMessage.ProtoReflect.Descriptor instead.
func (*PairResponseMessage) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{1}
}

func (x *PairResponseMessage) GetResult() *DeRecResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *PairResponseMessage) GetCommunicationInfo() *CommunicationInfo {
	if x != nil {
		return x.CommunicationInfo
	}
	return nil
}

func (x *PairResponseMessage) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *PairResponseMessage) GetParameterRange() *ParameterRange {
	if x != nil {
		return x.ParameterRange
	}
	return nil
}

func (x *PairResponseMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PairResponseMessage) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

var File_pair_proto protoreflect.FileDescriptor

const file_pair_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"pair.proto\x12 org.derecalliance.derec.protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17communicationinfo.proto\x1a\x14parameterrange.proto\x1a\fresult.proto\x1a\x17transportprotocol.proto\"\xa4\x04\n" +
	"\x12PairRequestMessage\x12L\n" +
	"\n" +
	"senderKind\x18\x01 \x01(\x0e2,.org.derecalliance.derec.protobuf.SenderKindR\n" +
	"senderKind\x12(\n" +
	"\x0fmlkemCiphertext\x18\x02 \x01(\fR\x0fmlkemCiphertext\x12&\n" +
	"\x0eeciesPublicKey\x18\x03 \x01(\fR\x0eeciesPublicKey\x12a\n" +
	"\x11communicationInfo\x18\x05 \x01(\v23.org.derecalliance.derec.protobuf.CommunicationInfoR\x11communicationInfo\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\x04R\x05nonce\x12X\n" +
	"\x0eparameterRange\x18\a \x01(\v20.org.derecalliance.derec.protobuf.ParameterRangeR\x0eparameterRange\x12a\n" +
	"\x11transportProtocol\x18\b \x01(\v23.org.derecalliance.derec.protobuf.TransportProtocolR\x11transportProtocol\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x87\x03\n" +
	"\x13PairResponseMessage\x12E\n" +
	"\x06result\x18\x01 \x01(\v2-.org.derecalliance.derec.protobuf.DeRecResultR\x06result\x12a\n" +
	"\x11communicationInfo\x18\x04 \x01(\v23.org.derecalliance.derec.protobuf.CommunicationInfoR\x11communicationInfo\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\x04R\x05nonce\x12X\n" +
	"\x0eparameterRange\x18\x06 \x01(\v20.org.derecalliance.derec.protobuf.ParameterRangeR\x0eparameterRange\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\tchannelId\x18\b \x01(\x04R\tchannelId*P\n" +
	"\n" +
	"SenderKind\x12\t\n" +
	"\x05OWNER\x10\x00\x12\n" +
	"\n" +
	"\x06HELPER\x10\x01\x12\x12\n" +
	"\x0eREPLICA_SOURCE\x10\x03\x12\x17\n" +
	"\x13REPLICA_DESTINATION\x10\x04b\x06proto3"

var (
	file_pair_proto_rawDescOnce sync.Once
	file_pair_proto_rawDescData []byte
)

func file_pair_proto_rawDescGZIP() []byte {
	file_pair_proto_rawDescOnce.Do(func() {
		file_pair_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pair_proto_rawDesc), len(file_pair_proto_rawDesc)))
	})
	return file_pair_proto_rawDescData
}

var file_pair_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pair_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pair_proto_goTypes = []any{
	(SenderKind)(0),               // 0: org.derecalliance.derec.protobuf.SenderKind
	(*PairRequestMessage)(nil),    // 1: org.derecalliance.derec.protobuf.PairRequestMessage
	(*PairResponseMessage)(nil),   // 2: org.derecalliance.derec.protobuf.PairResponseMessage
	(*CommunicationInfo)(nil),     // 3: org.derecalliance.derec.protobuf.CommunicationInfo
	(*ParameterRange)(nil),        // 4: org.derecalliance.derec.protobuf.ParameterRange
	(*TransportProtocol)(nil),     // 5: org.derecalliance.derec.protobuf.TransportProtocol
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*DeRecResult)(nil),           // 7: org.derecalliance.derec.protobuf.DeRecResult
}
var file_pair_proto_depIdxs = []int32{
	0, // 0: org.derecalliance.derec.protobuf.PairRequestMessage.senderKind:type_name -> org.derecalliance.derec.protobuf.SenderKind
	3, // 1: org.derecalliance.derec.protobuf.PairRequestMessage.communicationInfo:type_name -> org.derecalliance.derec.protobuf.CommunicationInfo
	4, // 2: org.derecalliance.derec.protobuf.PairRequestMessage.parameterRange:type_name -> org.derecalliance.derec.protobuf.ParameterRange
	5, // 3: org.derecalliance.derec.protobuf.PairRequestMessage.transportProtocol:type_name -> org.derecalliance.derec.protobuf.TransportProtocol
	6, // 4: org.derecalliance.derec.protobuf.PairRequestMessage.timestamp:type_name -> google.protobuf.Timestamp
	7, // 5: org.derecalliance.derec.protobuf.PairResponseMessage.result:type_name -> org.derecalliance.derec.protobuf.DeRecResult
	3, // 6: org.derecalliance.derec.protobuf.PairResponseMessage.communicationInfo:type_name -> org.derecalliance.derec.protobuf.CommunicationInfo
	4, // 7: org.derecalliance.derec.protobuf.PairResponseMessage.parameterRange:type_name -> org.derecalliance.derec.protobuf.ParameterRange
	6, // 8: org.derecalliance.derec.protobuf.PairResponseMessage.timestamp:type_name -> google.protobuf.Timestamp
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_pair_proto_init() }
func file_pair_proto_init() {
	if File_pair_proto != nil {
		return
	}
	file_communicationinfo_proto_init()
	file_parameterrange_proto_init()
	file_result_proto_init()
	file_transportprotocol_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pair_proto_rawDesc), len(file_pair_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pair_proto_goTypes,
		DependencyIndexes: file_pair_proto_depIdxs,
		EnumInfos:         file_pair_proto_enumTypes,
		MessageInfos:      file_pair_proto_msgTypes,
	}.Build()
	File_pair_proto = out.File
	file_pair_proto_goTypes = nil
	file_pair_proto_depIdxs = nil
}
