//
// Copyright (c) DeRec Alliance and its Contributors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: parameterrange.proto

package derecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParameterRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minimum and maximum number of bytes the party is willing to store
	// at any given time.
	MinShareSize int64 `protobuf:"varint,1,opt,name=minShareSize,proto3" json:"minShareSize,omitempty"`
	MaxShareSize int64 `protobuf:"varint,2,opt,name=maxShareSize,proto3" json:"maxShareSize,omitempty"`
	// Minimum and maximum interval between verification requests that
	// will be accepted.
	MinTimeBetweenVerifications int64 `protobuf:"varint,3,opt,name=minTimeBetweenVerifications,proto3" json:"minTimeBetweenVerifications,omitempty"`
	MaxTimeBetweenVerifications int64 `protobuf:"varint,4,opt,name=maxTimeBetweenVerifications,proto3" json:"maxTimeBetweenVerifications,omitempty"`
	// Minimum and maximum interval between accepting new share updates.
	MinTimeBetweenShareUpdates int64 `protobuf:"varint,5,opt,name=minTimeBetweenShareUpdates,proto3" json:"minTimeBetweenShareUpdates,omitempty"`
	MaxTimeBetweenShareUpdates int64 `protobuf:"varint,6,opt,name=maxTimeBetweenShareUpdates,proto3" json:"maxTimeBetweenShareUpdates,omitempty"`
	// Minimum and maximum timeout period (in seconds) after which the
	// other party is considered unresponsive and the pairing may be
	// removed along with all associated data.
	MinUnresponsiveDeletionTimeout int64 `protobuf:"varint,7,opt,name=minUnresponsiveDeletionTimeout,proto3" json:"minUnresponsiveDeletionTimeout,omitempty"`
	MaxUnresponsiveDeletionTimeout int64 `protobuf:"varint,8,opt,name=maxUnresponsiveDeletionTimeout,proto3" json:"maxUnresponsiveDeletionTimeout,omitempty"`
	// Minimum and maximum timeout period (in seconds) after which the
	// other party is considered inactive.
	MinUnresponsiveDeactivationTimeout int64 `protobuf:"varint,9,opt,name=minUnresponsiveDeactivationTimeout,proto3" json:"minUnresponsiveDeactivationTimeout,omitempty"`
	MaxUnresponsiveDeactivationTimeout int64 `protobuf:"varint,10,opt,name=maxUnresponsiveDeactivationTimeout,proto3" json:"maxUnresponsiveDeactivationTimeout,omitempty"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *ParameterRange) Reset() {
	*x = ParameterRange{}
	mi := &file_parameterrange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterRange) ProtoMessage() {}

func (x *ParameterRange) ProtoReflect() protoreflect.Message {
	mi := &file_parameterrange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterRange.ProtoReflect.Descriptor instead.
func (*ParameterRange) Descriptor() ([]byte, []int) {
	return file_parameterrange_proto_rawDescGZIP(), []int{0}
}

func (x *ParameterRange) GetMinShareSize() int64 {
	if x != nil {
		return x.MinShareSize
	}
	return 0
}

func (x *ParameterRange) GetMaxShareSize() int64 {
	if x != nil {
		return x.MaxShareSize
	}
	return 0
}

func (x *ParameterRange) GetMinTimeBetweenVerifications() int64 {
	if x != nil {
		return x.MinTimeBetweenVerifications
	}
	return 0
}

func (x *ParameterRange) GetMaxTimeBetweenVerifications() int64 {
	if x != nil {
		return x.MaxTimeBetweenVerifications
	}
	return 0
}

func (x *ParameterRange) GetMinTimeBetweenShareUpdates() int64 {
	if x != nil {
		return x.MinTimeBetweenShareUpdates
	}
	return 0
}

func (x *ParameterRange) GetMaxTimeBetweenShareUpdates() int64 {
	if x != nil {
		return x.MaxTimeBetweenShareUpdates
	}
	return 0
}

func (x *ParameterRange) GetMinUnresponsiveDeletionTimeout() int64 {
	if x != nil {
		return x.MinUnresponsiveDeletionTimeout
	}
	return 0
}

func (x *ParameterRange) GetMaxUnresponsiveDeletionTimeout() int64 {
	if x != nil {
		return x.MaxUnresponsiveDeletionTimeout
	}
	return 0
}

func (x *ParameterRange) GetMinUnresponsiveDeactivationTimeout() int64 {
	if x != nil {
		return x.MinUnresponsiveDeactivationTimeout
	}
	return 0
}

func (x *ParameterRange) GetMaxUnresponsiveDeactivationTimeout() int64 {
	if x != nil {
		return x.MaxUnresponsiveDeactivationTimeout
	}
	return 0
}

var File_parameterrange_proto protoreflect.FileDescriptor

const file_parameterrange_proto_rawDesc = "" +
	"\n" +
	"\x14parameterrange.proto\x12 org.derecalliance.derec.protobuf\"\x8c\x05\n" +
	"\x0eParameterRange\x12\"\n" +
	"\fminShareSize\x18\x01 \x01(\x03R\fminShareSize\x12\"\n" +
	"\fmaxShareSize\x18\x02 \x01(\x03R\fmaxShareSize\x12@\n" +
	"\x1bminTimeBetweenVerifications\x18\x03 \x01(\x03R\x1bminTimeBetweenVerifications\x12@\n" +
	"\x1bmaxTimeBetweenVerifications\x18\x04 \x01(\x03R\x1bmaxTimeBetweenVerifications\x12>\n" +
	"\x1aminTimeBetweenShareUpdates\x18\x05 \x01(\x03R\x1aminTimeBetweenShareUpdates\x12>\n" +
	"\x1amaxTimeBetweenShareUpdates\x18\x06 \x01(\x03R\x1amaxTimeBetweenShareUpdates\x12F\n" +
	"\x1eminUnresponsiveDeletionTimeout\x18\a \x01(\x03R\x1eminUnresponsiveDeletionTimeout\x12F\n" +
	"\x1emaxUnresponsiveDeletionTimeout\x18\b \x01(\x03R\x1emaxUnresponsiveDeletionTimeout\x12N\n" +
	"\"minUnresponsiveDeactivationTimeout\x18\t \x01(\x03R\"minUnresponsiveDeactivationTimeout\x12N\n" +
	"\"maxUnresponsiveDeactivationTimeout\x18\n" +
	" \x01(\x03R\"maxUnresponsiveDeactivationTimeoutb\x06proto3"

var (
	file_parameterrange_proto_rawDescOnce sync.Once
	file_parameterrange_proto_rawDescData []byte
)

func file_parameterrange_proto_rawDescGZIP() []byte {
	file_parameterrange_proto_rawDescOnce.Do(func() {
		file_parameterrange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_parameterrange_proto_rawDesc), len(file_parameterrange_proto_rawDesc)))
	})
	return file_parameterrange_proto_rawDescData
}

var file_parameterrange_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_parameterrange_proto_goTypes = []any{
	(*ParameterRange)(nil), // 0: org.derecalliance.derec.protobuf.ParameterRange
}
var file_parameterrange_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_parameterrange_proto_init() }
func file_parameterrange_proto_init() {
	if File_parameterrange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_parameterrange_proto_rawDesc), len(file_parameterrange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_parameterrange_proto_goTypes,
		DependencyIndexes: file_parameterrange_proto_depIdxs,
		MessageInfos:      file_parameterrange_proto_msgTypes,
	}.Build()
	File_parameterrange_proto = out.File
	file_parameterrange_proto_goTypes = nil
	file_parameterrange_proto_depIdxs = nil
}
