//
// Copyright (c) DeRec Alliance and its Contributors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: prepair.proto

package derecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PrePairRequestMessage is sent by the recipient of a ContactMessage whose
// `contactMode == CONTACT_MODE_HASHED_KEYS`. It asks the contact creator for
// the actual ML-KEM and ECIES public keys that the contact's
// `contactBindingHash` commits to.
//
// # When this is sent
//
// `CONTACT_MODE_HASHED_KEYS` contacts carry only a hash of the public keys
// so they fit in size-constrained out-of-band channels (e.g. QR codes,
// short URLs). The recipient must obtain the actual keys before it can
// construct the first encrypted `PairRequestMessage`.
//
// # Security
//
// This message is plaintext — no shared key has been established yet. The
// scanner-side integrity check happens after the `PrePairResponseMessage`
// arrives, by recomputing the hash and matching it against the original
// `contactBindingHash`. An attacker who intercepts the transport cannot
// substitute different keys without producing a hash collision.
//
// # Envelope
//
// The message is wrapped in a `DeRecMessage` envelope just like every
// other protocol message. The envelope's `channelId` carries the routing
// key; the envelope's `message` field carries the serialized
// `PrePairRequestMessage` bytes unencrypted (because no symmetric key
// exists yet).
//
// # Security: transport endpoint is observable
//
// Because the envelope is plaintext, the `transportProtocol` field in both
// `PrePairRequestMessage` and `PrePairResponseMessage` is visible to any
// passive observer on the network path. The same applies to the
// `transportProtocol` carried in the `HASHED_KEYS`-mode `ContactMessage`
// itself if its out-of-band channel can be observed.
//
// The protocol relies on this contract from the application to preserve
// the security guarantees of `HASHED_KEYS` mode:
//
//   - The `transportProtocol` used during pairing (the one advertised in the
//     `ContactMessage` and echoed in `PrePairRequestMessage`) MUST be
//     ephemeral and short-lived — bound to the pairing attempt, not to the
//     long-term identity of either peer.
//   - Once pairing completes, the application MUST swap to a long-term
//     endpoint via an `UpdateChannelInfoRequestMessage`. The ephemeral
//     pairing endpoint is retired after the changeover (see the endpoint-
//     changeover discipline on `UpdateChannelInfoRequestMessage`).
//
// `INLINE_KEYS`-mode contacts do not have this constraint because the
// `PairRequestMessage` is asymmetrically encrypted; only the
// `ContactMessage` itself crosses an unencrypted channel, which is by
// definition the trusted out-of-band one.
type PrePairRequestMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The same `nonce` the original `ContactMessage` advertised. Bound to
	// the contact session; mismatches indicate a stale or spoofed request
	// and the receiver MUST refuse to serve the keys.
	Nonce uint64 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Transport endpoint at which the sender expects to receive the
	// `PrePairResponseMessage`.
	//
	// Deprecated: superseded by `supportedTransports`, which carries every
	// endpoint rather than one.
	//
	// **Reading this field directly is now incorrect.** Its meaning narrowed
	// from "the endpoint" to "one entry of a list, and possibly absent": a
	// sender that has moved past this field advertises only
	// `supportedTransports`. A reader that was correct before this release is
	// a bug now — it rejects, or fails to reply to, a peer that is offering it
	// a perfectly good endpoint. Resolve both spellings instead of reading
	// either: `advertised_endpoints()` (Rust and TypeScript),
	// `AdvertisedEndpoints()` (Go), `AdvertisedEndpoints()` (.NET).
	//
	// Senders still populate it: a sender that sets `supportedTransports`
	// MUST also set this to a single best-compatibility choice, so
	// implementations predating the list still receive a reply.
	//
	// **Scheduled for removal in v0.0.5.**
	//
	// Deprecated: Marked as deprecated in prepair.proto.
	TransportProtocol *TransportProtocol `protobuf:"bytes,2,opt,name=transportProtocol,proto3" json:"transportProtocol,omitempty"`
	// Timestamp indicating when this message was created.
	//
	// This value is expressed in UTC and is used for envelope-vs-body
	// timestamp validation, replay detection, and observability.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Every transport endpoint the sender of this PrePair request can be
	// reached on for the `PrePairResponseMessage`.
	//
	// Each entry is a complete endpoint: a URI plus the protocol that says
	// how to interpret it. The list is written in the sender's own
	// preference order.
	//
	// # Selection is the recipient's
	//
	// A recipient picks whichever entry suits it, ordered by its **own**
	// preference rather than the sender's. The order here expresses
	// availability, not a ranking the recipient must honor.
	//
	// # Compatibility
	//
	// Absent means "only `transportProtocol` is offered", which is how every
	// implementation predating this field behaves. A sender populating this
	// list MUST also set `transportProtocol` to a single best-compatibility
	// choice so those implementations still reply.
	//
	// At least one of the two MUST be present: a request naming no endpoint
	// gives the recipient nowhere to send the response.
	//
	// # Security
	//
	// PrePair traffic is plaintext — no shared key exists yet — so these
	// endpoints are visible to a passive observer, exactly as
	// `transportProtocol` already was. The recipient's transport policy still
	// refuses plaintext entries unless plaintext has been opted into.
	SupportedTransports []*TransportProtocol `protobuf:"bytes,4,rep,name=supportedTransports,proto3" json:"supportedTransports,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PrePairRequestMessage) Reset() {
	*x = PrePairRequestMessage{}
	mi := &file_prepair_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePairRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePairRequestMessage) ProtoMessage() {}

func (x *PrePairRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_prepair_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePairRequestMessage.ProtoReflect.Descriptor instead.
func (*PrePairRequestMessage) Descriptor() ([]byte, []int) {
	return file_prepair_proto_rawDescGZIP(), []int{0}
}

func (x *PrePairRequestMessage) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

// Deprecated: Marked as deprecated in prepair.proto.
func (x *PrePairRequestMessage) GetTransportProtocol() *TransportProtocol {
	if x != nil {
		return x.TransportProtocol
	}
	return nil
}

func (x *PrePairRequestMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PrePairRequestMessage) GetSupportedTransports() []*TransportProtocol {
	if x != nil {
		return x.SupportedTransports
	}
	return nil
}

// PrePairResponseMessage is the contact creator's reply to a
// `PrePairRequestMessage`. On success it carries the real public keys; on
// failure it carries only a non-`Ok` `DeRecResult`.
//
// # Validation by the receiver
//
// The recipient (the original scanner of the `ContactMessage`) MUST:
//
//   - Confirm `result.status == OK`. On non-`Ok`, surface a typed error to
//     the application and do not proceed.
//
//   - Recompute
//
//     ```text
//     SHA-384(mlkemEncapsulationKey || eciesPublicKey
//     || u64_be(nonce) || u64_be(channelId))
//     ```
//
//     and verify it matches the original `ContactMessage.contactBindingHash`.
//   - Only on a match, proceed to construct and send a normal
//     `PairRequestMessage`.
//
// # Envelope
//
// Plaintext-in-`DeRecMessage`-envelope, same as `PrePairRequestMessage`.
type PrePairResponseMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result of processing the `PrePairRequestMessage`. On `OK`, the two
	// key fields below are present. On any non-`Ok` status, the key fields
	// MUST be absent.
	Result *DeRecResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// Serialized ML-KEM-768 encapsulation key. Present only when
	// `result.status == OK`.
	MlkemEncapsulationKey []byte `protobuf:"bytes,2,opt,name=mlkemEncapsulationKey,proto3,oneof" json:"mlkemEncapsulationKey,omitempty"`
	// Serialized ECIES public key. Present only when
	// `result.status == OK`.
	EciesPublicKey []byte `protobuf:"bytes,3,opt,name=eciesPublicKey,proto3,oneof" json:"eciesPublicKey,omitempty"`
	// Echoed from the request for session correlation.
	Nonce uint64 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Timestamp indicating when this message was created.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrePairResponseMessage) Reset() {
	*x = PrePairResponseMessage{}
	mi := &file_prepair_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePairResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePairResponseMessage) ProtoMessage() {}

func (x *PrePairResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_prepair_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePairResponseMessage.ProtoReflect.Descriptor instead.
func (*PrePairResponseMessage) Descriptor() ([]byte, []int) {
	return file_prepair_proto_rawDescGZIP(), []int{1}
}

func (x *PrePairResponseMessage) GetResult() *DeRecResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *PrePairResponseMessage) GetMlkemEncapsulationKey() []byte {
	if x != nil {
		return x.MlkemEncapsulationKey
	}
	return nil
}

func (x *PrePairResponseMessage) GetEciesPublicKey() []byte {
	if x != nil {
		return x.EciesPublicKey
	}
	return nil
}

func (x *PrePairResponseMessage) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *PrePairResponseMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_prepair_proto protoreflect.FileDescriptor

const file_prepair_proto_rawDesc = "" +
	"\n" +
	"\rprepair.proto\x12 org.derecalliance.derec.protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fresult.proto\x1a\x17transportprotocol.proto\"\xb5\x02\n" +
	"\x15PrePairRequestMessage\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\x12e\n" +
	"\x11transportProtocol\x18\x02 \x01(\v23.org.derecalliance.derec.protobuf.TransportProtocolB\x02\x18\x01R\x11transportProtocol\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12e\n" +
	"\x13supportedTransports\x18\x04 \x03(\v23.org.derecalliance.derec.protobuf.TransportProtocolR\x13supportedTransports\"\xc4\x02\n" +
	"\x16PrePairResponseMessage\x12E\n" +
	"\x06result\x18\x01 \x01(\v2-.org.derecalliance.derec.protobuf.DeRecResultR\x06result\x129\n" +
	"\x15mlkemEncapsulationKey\x18\x02 \x01(\fH\x00R\x15mlkemEncapsulationKey\x88\x01\x01\x12+\n" +
	"\x0eeciesPublicKey\x18\x03 \x01(\fH\x01R\x0eeciesPublicKey\x88\x01\x01\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\x04R\x05nonce\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB\x18\n" +
	"\x16_mlkemEncapsulationKeyB\x11\n" +
	"\x0f_eciesPublicKeyb\x06proto3"

var (
	file_prepair_proto_rawDescOnce sync.Once
	file_prepair_proto_rawDescData []byte
)

func file_prepair_proto_rawDescGZIP() []byte {
	file_prepair_proto_rawDescOnce.Do(func() {
		file_prepair_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_prepair_proto_rawDesc), len(file_prepair_proto_rawDesc)))
	})
	return file_prepair_proto_rawDescData
}

var file_prepair_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_prepair_proto_goTypes = []any{
	(*PrePairRequestMessage)(nil),  // 0: org.derecalliance.derec.protobuf.PrePairRequestMessage
	(*PrePairResponseMessage)(nil), // 1: org.derecalliance.derec.protobuf.PrePairResponseMessage
	(*TransportProtocol)(nil),      // 2: org.derecalliance.derec.protobuf.TransportProtocol
	(*timestamppb.Timestamp)(nil),  // 3: google.protobuf.Timestamp
	(*DeRecResult)(nil),            // 4: org.derecalliance.derec.protobuf.DeRecResult
}
var file_prepair_proto_depIdxs = []int32{
	2, // 0: org.derecalliance.derec.protobuf.PrePairRequestMessage.transportProtocol:type_name -> org.derecalliance.derec.protobuf.TransportProtocol
	3, // 1: org.derecalliance.derec.protobuf.PrePairRequestMessage.timestamp:type_name -> google.protobuf.Timestamp
	2, // 2: org.derecalliance.derec.protobuf.PrePairRequestMessage.supportedTransports:type_name -> org.derecalliance.derec.protobuf.TransportProtocol
	4, // 3: org.derecalliance.derec.protobuf.PrePairResponseMessage.result:type_name -> org.derecalliance.derec.protobuf.DeRecResult
	3, // 4: org.derecalliance.derec.protobuf.PrePairResponseMessage.timestamp:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_prepair_proto_init() }
func file_prepair_proto_init() {
	if File_prepair_proto != nil {
		return
	}
	file_result_proto_init()
	file_transportprotocol_proto_init()
	file_prepair_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_prepair_proto_rawDesc), len(file_prepair_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_prepair_proto_goTypes,
		DependencyIndexes: file_prepair_proto_depIdxs,
		MessageInfos:      file_prepair_proto_msgTypes,
	}.Build()
	File_prepair_proto = out.File
	file_prepair_proto_goTypes = nil
	file_prepair_proto_depIdxs = nil
}
