//
// Copyright (c) DeRec Alliance and its Contributors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: secretidsversions.proto

package derecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetSecretIdsVersionsRequestMessage requests the list of all secrets and
// corresponding share versions that a Helper stores for a given Owner.
//
// # Context
//
// This message is used during the recovery flow, after the Owner has
// re-paired with a Helper (typically in recovery mode).
//
// Since the recovering Owner does not know which secrets or versions
// the Helper holds, this message allows discovery of:
//
// - all secretIds associated with the Owner
// - all share versions stored for each secret
//
// # Semantics
//
// The Helper responds with a GetSecretIdsVersionsResponseMessage containing:
//
// - one entry per secretId
// - the list of versions stored for each secret
//
// # Authorization Rules
//
// The Helper MUST only fully process this request if it is received through
// a communication channel that was established in recovery mode and has been
// associated (via authentication) with the same Owner as previously stored
// secrets.
//
// If this condition is not met, the Helper MAY:
//
// - return only partial information (e.g., for the current channel), or
// - reject the request entirely
//
// # Authentication
//
// The Helper MUST authenticate the requester at the application level before
// disclosing any information about stored secrets. Authentication is outside
// the scope of the protocol and may include:
//
// - in-person verification
// - KYC processes
// - biometrics or credentials
//
// # Idempotency
//
// This request is idempotent. Repeated requests SHOULD return the same
// information unless the underlying storage changes.
type GetSecretIdsVersionsRequestMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp indicating when this message was created.
	//
	// This value is expressed in UTC and can be used for:
	//
	// - observability and logging
	// - replay detection (in combination with sequence numbers)
	// - timeout handling
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Ephemeral transport endpoint at which the requester wants to receive
	// the response to *this exchange*, overriding the channel's stored peer
	// endpoint for this round-trip only.
	//
	// See `StoreShareRequestMessage.replyTo` for full semantics. Absent =
	// route to the stored channel endpoint; Present = route this response
	// here without persisting the endpoint.
	ReplyTo       *TransportProtocol `protobuf:"bytes,2,opt,name=replyTo,proto3,oneof" json:"replyTo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretIdsVersionsRequestMessage) Reset() {
	*x = GetSecretIdsVersionsRequestMessage{}
	mi := &file_secretidsversions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretIdsVersionsRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretIdsVersionsRequestMessage) ProtoMessage() {}

func (x *GetSecretIdsVersionsRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_secretidsversions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretIdsVersionsRequestMessage.ProtoReflect.Descriptor instead.
func (*GetSecretIdsVersionsRequestMessage) Descriptor() ([]byte, []int) {
	return file_secretidsversions_proto_rawDescGZIP(), []int{0}
}

func (x *GetSecretIdsVersionsRequestMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GetSecretIdsVersionsRequestMessage) GetReplyTo() *TransportProtocol {
	if x != nil {
		return x.ReplyTo
	}
	return nil
}

// GetSecretIdsVersionsResponseMessage returns the list of all secrets and
// their corresponding share versions stored by the Helper for the Owner.
//
// # Semantics
//
// Each entry in `secretList` represents:
//
// - a `secretId` previously shared by the Owner
// - the list of share versions currently stored for that secret
//
// This allows the recovering Owner to:
//
// - discover which secrets exist
// - determine which versions to request via GetShareRequestMessage
//
// # Authorization and Privacy
//
// The Helper MUST ensure that:
//
// - the requester is authenticated as the same Owner
// - the request originates from a recovery-mode channel
//
// Only under these conditions may the Helper return the full list of secrets.
//
// Otherwise, the Helper MUST:
//
// - return partial data (e.g., only for the current secretId), or
// - return a failure result
//
// # Security Considerations
//
// - This message reveals metadata about stored secrets
// - It MUST only be sent over an authenticated and encrypted channel
// - Unauthorized disclosure could leak information about user activity
//
// # Idempotency
//
// For a given Helper state, repeated responses SHOULD return the same data.
type GetSecretIdsVersionsResponseMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result of processing the request.
	//
	// Indicates whether the request was successfully processed or rejected.
	Result *DeRecResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// List of secrets and their stored versions.
	//
	// Each entry corresponds to one secretId and the versions available
	// for that secret.
	SecretList []*GetSecretIdsVersionsResponseMessage_VersionList `protobuf:"bytes,2,rep,name=secretList,proto3" json:"secretList,omitempty"`
	// Timestamp indicating when this message was created.
	//
	// This value is expressed in UTC and can be used for:
	//
	// - observability and logging
	// - replay detection (in combination with sequence numbers)
	// - timeout handling
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretIdsVersionsResponseMessage) Reset() {
	*x = GetSecretIdsVersionsResponseMessage{}
	mi := &file_secretidsversions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretIdsVersionsResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretIdsVersionsResponseMessage) ProtoMessage() {}

func (x *GetSecretIdsVersionsResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_secretidsversions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretIdsVersionsResponseMessage.ProtoReflect.Descriptor instead.
func (*GetSecretIdsVersionsResponseMessage) Descriptor() ([]byte, []int) {
	return file_secretidsversions_proto_rawDescGZIP(), []int{1}
}

func (x *GetSecretIdsVersionsResponseMessage) GetResult() *DeRecResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetSecretIdsVersionsResponseMessage) GetSecretList() []*GetSecretIdsVersionsResponseMessage_VersionList {
	if x != nil {
		return x.SecretList
	}
	return nil
}

func (x *GetSecretIdsVersionsResponseMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// VersionList groups the share versions stored for a single secretId.
//
// # Semantics
//
//   - `secretId` uniquely identifies a secret
//   - `versions` lists all share versions currently stored for that secret,
//     each paired with a human-readable description
//
// The order of versions is not significant unless defined by the
// implementation.
type GetSecretIdsVersionsResponseMessage_VersionList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the secret.
	SecretId uint64 `protobuf:"varint,1,opt,name=secretId,proto3" json:"secretId,omitempty"`
	// List of share versions stored for this secret.
	//
	// Each entry carries the numeric version identifier together with the
	// human-readable description that was supplied by the Owner when the
	// share was stored. Descriptions help the recovering Owner identify
	// which secret corresponds to which identifier without relying on
	// raw bytes alone.
	Versions      []*GetSecretIdsVersionsResponseMessage_VersionList_VersionEntry `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretIdsVersionsResponseMessage_VersionList) Reset() {
	*x = GetSecretIdsVersionsResponseMessage_VersionList{}
	mi := &file_secretidsversions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretIdsVersionsResponseMessage_VersionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretIdsVersionsResponseMessage_VersionList) ProtoMessage() {}

func (x *GetSecretIdsVersionsResponseMessage_VersionList) ProtoReflect() protoreflect.Message {
	mi := &file_secretidsversions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretIdsVersionsResponseMessage_VersionList.ProtoReflect.Descriptor instead.
func (*GetSecretIdsVersionsResponseMessage_VersionList) Descriptor() ([]byte, []int) {
	return file_secretidsversions_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetSecretIdsVersionsResponseMessage_VersionList) GetSecretId() uint64 {
	if x != nil {
		return x.SecretId
	}
	return 0
}

func (x *GetSecretIdsVersionsResponseMessage_VersionList) GetVersions() []*GetSecretIdsVersionsResponseMessage_VersionList_VersionEntry {
	if x != nil {
		return x.Versions
	}
	return nil
}

// One stored version of a secret, paired with its human-readable label.
type GetSecretIdsVersionsResponseMessage_VersionList_VersionEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Numeric version identifier.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Human-readable description supplied by the Owner at share-storage time.
	//
	// May be empty if no description was provided.
	VersionDescription string `protobuf:"bytes,2,opt,name=versionDescription,proto3" json:"versionDescription,omitempty"`
	// Stable per-device identifier of the replica that produced this
	// version, copied from `StoreShareRequestMessage.replicaId` at
	// share-storage time.
	//
	// # Why per-version (and not per-secret)
	//
	// Two distinct replicas can independently produce the same numeric
	// `version` for the same `secretId` (each replica observes the
	// current latest version and increments it). The helper persists
	// both side-by-side; this field is what lets the recovering owner
	// tell them apart.
	//
	// # Semantics
	//
	//   - Absent: the version was produced by a non-replica `Owner`
	//     (the writer had no `replica_id` configured at the builder).
	//   - Present: the version was produced by the named replica.
	//
	// # Out of scope for the protocol
	//
	// The protocol surfaces this metadata so the application can
	// detect conflicts (e.g. two replicas both produced version 7 of
	// the same secret). Resolution is the application's
	// responsibility — typically: pick one, then re-run
	// `ProtectSecret` with the chosen value to produce a fresh,
	// uncontested version before driving recovery.
	ReplicaId     *uint64 `protobuf:"varint,3,opt,name=replicaId,proto3,oneof" json:"replicaId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretIdsVersionsResponseMessage_VersionList_VersionEntry) Reset() {
	*x = GetSecretIdsVersionsResponseMessage_VersionList_VersionEntry{}
	mi := &file_secretidsversions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretIdsVersionsResponseMessage_VersionList_VersionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretIdsVersionsResponseMessage_VersionList_VersionEntry) ProtoMessage() {}

func (x *GetSecretIdsVersionsResponseMessage_VersionList_VersionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_secretidsversions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretIdsVersionsResponseMessage_VersionList_VersionEntry.ProtoReflect.Descriptor instead.
func (*GetSecretIdsVersionsResponseMessage_VersionList_VersionEntry) Descriptor() ([]byte, []int) {
	return file_secretidsversions_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *GetSecretIdsVersionsResponseMessage_VersionList_VersionEntry) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetSecretIdsVersionsResponseMessage_VersionList_VersionEntry) GetVersionDescription() string {
	if x != nil {
		return x.VersionDescription
	}
	return ""
}

func (x *GetSecretIdsVersionsResponseMessage_VersionList_VersionEntry) GetReplicaId() uint64 {
	if x != nil && x.ReplicaId != nil {
		return *x.ReplicaId
	}
	return 0
}

var File_secretidsversions_proto protoreflect.FileDescriptor

const file_secretidsversions_proto_rawDesc = "" +
	"\n" +
	"\x17secretidsversions.proto\x12 org.derecalliance.derec.protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fresult.proto\x1a\x17transportprotocol.proto\"\xbe\x01\n" +
	"\"GetSecretIdsVersionsRequestMessage\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12R\n" +
	"\areplyTo\x18\x02 \x01(\v23.org.derecalliance.derec.protobuf.TransportProtocolH\x00R\areplyTo\x88\x01\x01B\n" +
	"\n" +
	"\b_replyTo\"\xcd\x04\n" +
	"#GetSecretIdsVersionsResponseMessage\x12E\n" +
	"\x06result\x18\x01 \x01(\v2-.org.derecalliance.derec.protobuf.DeRecResultR\x06result\x12q\n" +
	"\n" +
	"secretList\x18\x02 \x03(\v2Q.org.derecalliance.derec.protobuf.GetSecretIdsVersionsResponseMessage.VersionListR\n" +
	"secretList\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a\xb1\x02\n" +
	"\vVersionList\x12\x1a\n" +
	"\bsecretId\x18\x01 \x01(\x04R\bsecretId\x12z\n" +
	"\bversions\x18\x02 \x03(\v2^.org.derecalliance.derec.protobuf.GetSecretIdsVersionsResponseMessage.VersionList.VersionEntryR\bversions\x1a\x89\x01\n" +
	"\fVersionEntry\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12.\n" +
	"\x12versionDescription\x18\x02 \x01(\tR\x12versionDescription\x12!\n" +
	"\treplicaId\x18\x03 \x01(\x04H\x00R\treplicaId\x88\x01\x01B\f\n" +
	"\n" +
	"_replicaIdb\x06proto3"

var (
	file_secretidsversions_proto_rawDescOnce sync.Once
	file_secretidsversions_proto_rawDescData []byte
)

func file_secretidsversions_proto_rawDescGZIP() []byte {
	file_secretidsversions_proto_rawDescOnce.Do(func() {
		file_secretidsversions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_secretidsversions_proto_rawDesc), len(file_secretidsversions_proto_rawDesc)))
	})
	return file_secretidsversions_proto_rawDescData
}

var file_secretidsversions_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_secretidsversions_proto_goTypes = []any{
	(*GetSecretIdsVersionsRequestMessage)(nil),                           // 0: org.derecalliance.derec.protobuf.GetSecretIdsVersionsRequestMessage
	(*GetSecretIdsVersionsResponseMessage)(nil),                          // 1: org.derecalliance.derec.protobuf.GetSecretIdsVersionsResponseMessage
	(*GetSecretIdsVersionsResponseMessage_VersionList)(nil),              // 2: org.derecalliance.derec.protobuf.GetSecretIdsVersionsResponseMessage.VersionList
	(*GetSecretIdsVersionsResponseMessage_VersionList_VersionEntry)(nil), // 3: org.derecalliance.derec.protobuf.GetSecretIdsVersionsResponseMessage.VersionList.VersionEntry
	(*timestamppb.Timestamp)(nil),                                        // 4: google.protobuf.Timestamp
	(*TransportProtocol)(nil),                                            // 5: org.derecalliance.derec.protobuf.TransportProtocol
	(*DeRecResult)(nil),                                                  // 6: org.derecalliance.derec.protobuf.DeRecResult
}
var file_secretidsversions_proto_depIdxs = []int32{
	4, // 0: org.derecalliance.derec.protobuf.GetSecretIdsVersionsRequestMessage.timestamp:type_name -> google.protobuf.Timestamp
	5, // 1: org.derecalliance.derec.protobuf.GetSecretIdsVersionsRequestMessage.replyTo:type_name -> org.derecalliance.derec.protobuf.TransportProtocol
	6, // 2: org.derecalliance.derec.protobuf.GetSecretIdsVersionsResponseMessage.result:type_name -> org.derecalliance.derec.protobuf.DeRecResult
	2, // 3: org.derecalliance.derec.protobuf.GetSecretIdsVersionsResponseMessage.secretList:type_name -> org.derecalliance.derec.protobuf.GetSecretIdsVersionsResponseMessage.VersionList
	4, // 4: org.derecalliance.derec.protobuf.GetSecretIdsVersionsResponseMessage.timestamp:type_name -> google.protobuf.Timestamp
	3, // 5: org.derecalliance.derec.protobuf.GetSecretIdsVersionsResponseMessage.VersionList.versions:type_name -> org.derecalliance.derec.protobuf.GetSecretIdsVersionsResponseMessage.VersionList.VersionEntry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_secretidsversions_proto_init() }
func file_secretidsversions_proto_init() {
	if File_secretidsversions_proto != nil {
		return
	}
	file_result_proto_init()
	file_transportprotocol_proto_init()
	file_secretidsversions_proto_msgTypes[0].OneofWrappers = []any{}
	file_secretidsversions_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secretidsversions_proto_rawDesc), len(file_secretidsversions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_secretidsversions_proto_goTypes,
		DependencyIndexes: file_secretidsversions_proto_depIdxs,
		MessageInfos:      file_secretidsversions_proto_msgTypes,
	}.Build()
	File_secretidsversions_proto = out.File
	file_secretidsversions_proto_goTypes = nil
	file_secretidsversions_proto_depIdxs = nil
}
