//
// Copyright (c) DeRec Alliance and its Contributors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: storeshare.proto

package derecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StoreShareRequestMessage instructs a Helper to store a share for a given
// secret and manage the set of retained share versions.
//
// # Context
//
// This message is used in the sharing flow when:
//
// - a new secret is created
// - an existing secret is updated
// - the helper set or recovery threshold changes
//
// The Owner sends this message to each Helper to:
//
// - store (or replace) a specific share version
// - update the set of versions that must be retained (keepList)
//
// # Semantics
//
// This message may carry two independent instructions:
//
// 1. Share storage/update:
//   - If `share` is present, the Helper MUST store this share under the
//     specified `version`
//   - If the version already exists, the Helper MUST replace it
//
// 2. Retention policy update:
//   - If `keepList` is present, it defines the complete set of versions
//     that MUST be retained
//   - Any stored version not in `keepList` SHOULD be deleted
//
// If `keepList` is absent:
//
// - The Helper MUST preserve the existing keepList
// - The Helper MUST add the new `version` to the retained set
//
// # Consistency Requirements
//
// The Owner MUST ensure that for a given (secretId, version):
//
// - all Helpers receive identical share contents
//
// It is an error for different shares to be associated with the same
// version and secretId.
//
// # Replay Protection
//
// To prevent replay attacks:
//
//   - If `version` is less than the latest stored version,
//     the Helper MUST ignore the `keepList` field
//
// This ensures that stale messages cannot cause deletion of newer shares.
//
// # Share Opacity
//
// The Helper MUST treat the `share` field as opaque data. It is not required
// to understand or validate the share contents.
//
// # Idempotency
//
// This message is idempotent:
//
// - Re-sending the same (version, share) pair SHOULD result in the same state
// - Re-applying the same keepList SHOULD not change state after the first time
type StoreShareRequestMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Share bytes to be stored by the Helper.
	//
	// This is an opaque byte array produced by the share distribution
	// algorithm. The Helper MUST store it without interpretation.
	Share []byte `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	// Identifier of the algorithm used to produce the share.
	//
	// This allows the Owner and Helper to coordinate on how the share
	// should be interpreted during recovery.
	//
	// Algorithm 0 defines the share as a serialized `CommittedDeRecShare`
	// protobuf message (see DeRec cryptography repository).
	//
	// Implementations SHOULD support algorithm 0 for interoperability.
	ShareAlgorithm int32 `protobuf:"varint,2,opt,name=shareAlgorithm,proto3" json:"shareAlgorithm,omitempty"`
	// Identifier of the secret to which this share belongs.
	//
	// Used by the Helper to associate the share with the correct secret in the
	// share store under the composite key (channel_id, secret_id, version).
	SecretId uint64 `protobuf:"varint,3,opt,name=secretId,proto3" json:"secretId,omitempty"`
	// Version number of the share.
	//
	// Each resharing event increments this value.
	Version uint32 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	// List of share versions that MUST be retained by the Helper.
	//
	// Any stored version not included in this list SHOULD be deleted.
	//
	// If absent, the Helper MUST:
	//
	// - retain the existing keepList
	// - add the current `version` to the retained set
	//
	// This field MUST be ignored if `version` is older than the latest
	// version already stored, to prevent replay attacks.
	KeepList []uint32 `protobuf:"varint,5,rep,packed,name=keepList,proto3" json:"keepList,omitempty"`
	// Optional human-readable description of this share version.
	//
	// This field is visible to the Helper and is not intended to carry
	// sensitive information. It may be used for debugging, labeling, or
	// user-facing display.
	VersionDescription string `protobuf:"bytes,6,opt,name=versionDescription,proto3" json:"versionDescription,omitempty"`
	// Timestamp indicating when this message was created.
	//
	// Used for observability, replay detection, and timeout handling.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Ephemeral transport endpoints at which the requester wants to receive
	// the response to *this exchange*, in its own preference order,
	// overriding the channel's stored peer endpoints for this round-trip
	// only.
	//
	// # When to use
	//
	// Set when the requester's outbound endpoint does not match the endpoint
	// the responder has on file for the channel — for example a replica
	// talking to a helper that was paired with a sibling replica. The
	// responder routes the response here but does NOT persist these
	// endpoints; use `UpdateChannelInfoRequestMessage` for permanent changes.
	//
	// # Semantics
	//
	//   - Absent (the default): the responder routes to the endpoints stored on
	//     its `Channel` record for this `channelId`.
	//   - Present: the responder routes this exchange's response here, and
	//     leaves the stored endpoints unchanged.
	//
	// Superseded by `replyToTransports`, which carries every endpoint rather
	// than one. Kept, and still populated with the list's first entry, so
	// implementations predating that field still receive a reply.
	// **Scheduled for removal in v0.0.5.**
	//
	// **Reading this field directly is now incorrect** for the same reason it
	// is on `transportProtocol`: it is one entry of a list and may be absent.
	// Resolve it against `replyToTransports` instead.
	//
	// Deprecated: Marked as deprecated in storeshare.proto.
	ReplyTo *TransportProtocol `protobuf:"bytes,8,opt,name=replyTo,proto3,oneof" json:"replyTo,omitempty"`
	// Every ephemeral endpoint the requester wants this exchange's response
	// delivered to, in its own preference order.
	//
	// # Semantics
	//
	//   - Empty, and `replyTo` absent: the responder routes to the endpoints
	//     stored on its `Channel` record for this `channelId`.
	//   - Empty, `replyTo` present: that one endpoint, which is how every
	//     implementation predating this field asks.
	//   - Non-empty: the responder routes the response to any one of these, in
	//     the order given, and leaves the stored endpoints unchanged. Delivery
	//     to any one is success.
	//
	// # Why this is a new field rather than a wider `replyTo`
	//
	// `replyTo` was singular through 0.0.2. Re-tagging it `repeated` would
	// have been wire-compatible in the read direction only: protobuf merges a
	// repeated submessage into a singular reader field-by-field, so a 0.0.2
	// peer decoding a multi-entry list sees the **last** entry, while the
	// first entry is what every other compatibility rule in this release
	// designates as the legacy-readable one. One list cannot be ordered to
	// satisfy both. A new tag lets the singular field keep meaning exactly
	// what it did — the same shape `supportedTransports` (contact.proto tag 9)
	// uses beside `transportProtocol` (tag 7).
	ReplyToTransports []*TransportProtocol `protobuf:"bytes,10,rep,name=replyToTransports,proto3" json:"replyToTransports,omitempty"`
	// Identity of the replica that authored this update.
	//
	// # Audience
	//
	// This field is for **replicas only**. Helpers know nothing about
	// replicas and never receive it:
	//
	// - helper-bound (`SHARE_ALGORITHM_VSS`) — MUST be absent.
	// - replica-bound (`SHARE_ALGORITHM_REPLICA_SECRET`) — MUST be present.
	//
	// The invariant is `replicaId.is_some() == (shareAlgorithm ==
	// SHARE_ALGORITHM_REPLICA_SECRET)`, asserted on send and on receive; a
	// violation is a protocol error, not a tolerated variation.
	//
	// # Why the receiver needs it
	//
	// Every member of a replica group shares one `channelId`, so the
	// channel identifies the *group*, not the sender. The channel's
	// counterparty says who established it, which after admission by a
	// third member is not who wrote this message. Author attribution
	// therefore comes from this field and never from the channel record.
	//
	// Applications use it to resolve which member published an update, and
	// to route the response back to that member's endpoint.
	//
	// # Out of scope for the protocol
	//
	// The protocol does not authenticate the claim; anyone holding the
	// group key may write any `replicaId`. It is an identifier, not an
	// authenticator.
	ReplicaId     *uint64 `protobuf:"varint,9,opt,name=replicaId,proto3,oneof" json:"replicaId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreShareRequestMessage) Reset() {
	*x = StoreShareRequestMessage{}
	mi := &file_storeshare_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreShareRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreShareRequestMessage) ProtoMessage() {}

func (x *StoreShareRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_storeshare_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreShareRequestMessage.ProtoReflect.Descriptor instead.
func (*StoreShareRequestMessage) Descriptor() ([]byte, []int) {
	return file_storeshare_proto_rawDescGZIP(), []int{0}
}

func (x *StoreShareRequestMessage) GetShare() []byte {
	if x != nil {
		return x.Share
	}
	return nil
}

func (x *StoreShareRequestMessage) GetShareAlgorithm() int32 {
	if x != nil {
		return x.ShareAlgorithm
	}
	return 0
}

func (x *StoreShareRequestMessage) GetSecretId() uint64 {
	if x != nil {
		return x.SecretId
	}
	return 0
}

func (x *StoreShareRequestMessage) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StoreShareRequestMessage) GetKeepList() []uint32 {
	if x != nil {
		return x.KeepList
	}
	return nil
}

func (x *StoreShareRequestMessage) GetVersionDescription() string {
	if x != nil {
		return x.VersionDescription
	}
	return ""
}

func (x *StoreShareRequestMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Deprecated: Marked as deprecated in storeshare.proto.
func (x *StoreShareRequestMessage) GetReplyTo() *TransportProtocol {
	if x != nil {
		return x.ReplyTo
	}
	return nil
}

func (x *StoreShareRequestMessage) GetReplyToTransports() []*TransportProtocol {
	if x != nil {
		return x.ReplyToTransports
	}
	return nil
}

func (x *StoreShareRequestMessage) GetReplicaId() uint64 {
	if x != nil && x.ReplicaId != nil {
		return *x.ReplicaId
	}
	return 0
}

// StoreShareResponseMessage is the response to a StoreShareRequestMessage.
//
// # Semantics
//
// This message indicates whether the Helper successfully:
//
// - stored or updated the requested share version
// - applied the retention policy (keepList)
//
// # Idempotency
//
// Multiple identical requests SHOULD produce identical responses.
type StoreShareResponseMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result of processing the request.
	//
	// Indicates success or failure of the storage/update operation.
	Result *DeRecResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// Identifier of the secret to which this response refers.
	//
	// Echoed from the corresponding StoreShareRequestMessage so the Owner can
	// correlate responses with the correct secret without inspecting the share
	// bytes.
	SecretId uint64 `protobuf:"varint,2,opt,name=secretId,proto3" json:"secretId,omitempty"`
	// Version number from the corresponding request.
	//
	// This allows the sender to correlate responses with requests.
	Version uint32 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// Timestamp indicating when this message was created.
	//
	// Used for observability, replay detection, and timeout handling.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Identity of the replica that produced this response.
	//
	// Present only when the corresponding request was replica-bound
	// (`shareAlgorithm == SHARE_ALGORITHM_REPLICA_SECRET`); absent on
	// helper responses, which carry no replica identity in either
	// direction.
	//
	// # Why the requester needs it
	//
	// Every member of a replica group answers on the same `channelId`, and
	// `secretId` and `version` are echoed identically by all of them. Two
	// members responding to one publish are otherwise indistinguishable —
	// the requester cannot tell whether both acknowledged or one
	// acknowledged twice, and so cannot track a sharing round per member.
	ReplicaId     *uint64 `protobuf:"varint,5,opt,name=replicaId,proto3,oneof" json:"replicaId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreShareResponseMessage) Reset() {
	*x = StoreShareResponseMessage{}
	mi := &file_storeshare_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreShareResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreShareResponseMessage) ProtoMessage() {}

func (x *StoreShareResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_storeshare_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreShareResponseMessage.ProtoReflect.Descriptor instead.
func (*StoreShareResponseMessage) Descriptor() ([]byte, []int) {
	return file_storeshare_proto_rawDescGZIP(), []int{1}
}

func (x *StoreShareResponseMessage) GetResult() *DeRecResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *StoreShareResponseMessage) GetSecretId() uint64 {
	if x != nil {
		return x.SecretId
	}
	return 0
}

func (x *StoreShareResponseMessage) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StoreShareResponseMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StoreShareResponseMessage) GetReplicaId() uint64 {
	if x != nil && x.ReplicaId != nil {
		return *x.ReplicaId
	}
	return 0
}

var File_storeshare_proto protoreflect.FileDescriptor

const file_storeshare_proto_rawDesc = "" +
	"\n" +
	"\x10storeshare.proto\x12 org.derecalliance.derec.protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fresult.proto\x1a\x17transportprotocol.proto\"\x8c\x04\n" +
	"\x18StoreShareRequestMessage\x12\x14\n" +
	"\x05share\x18\x01 \x01(\fR\x05share\x12&\n" +
	"\x0eshareAlgorithm\x18\x02 \x01(\x05R\x0eshareAlgorithm\x12\x1a\n" +
	"\bsecretId\x18\x03 \x01(\x04R\bsecretId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\rR\aversion\x12\x1a\n" +
	"\bkeepList\x18\x05 \x03(\rR\bkeepList\x12.\n" +
	"\x12versionDescription\x18\x06 \x01(\tR\x12versionDescription\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12V\n" +
	"\areplyTo\x18\b \x01(\v23.org.derecalliance.derec.protobuf.TransportProtocolB\x02\x18\x01H\x00R\areplyTo\x88\x01\x01\x12a\n" +
	"\x11replyToTransports\x18\n" +
	" \x03(\v23.org.derecalliance.derec.protobuf.TransportProtocolR\x11replyToTransports\x12!\n" +
	"\treplicaId\x18\t \x01(\x04H\x01R\treplicaId\x88\x01\x01B\n" +
	"\n" +
	"\b_replyToB\f\n" +
	"\n" +
	"_replicaId\"\x83\x02\n" +
	"\x19StoreShareResponseMessage\x12E\n" +
	"\x06result\x18\x01 \x01(\v2-.org.derecalliance.derec.protobuf.DeRecResultR\x06result\x12\x1a\n" +
	"\bsecretId\x18\x02 \x01(\x04R\bsecretId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12!\n" +
	"\treplicaId\x18\x05 \x01(\x04H\x00R\treplicaId\x88\x01\x01B\f\n" +
	"\n" +
	"_replicaIdb\x06proto3"

var (
	file_storeshare_proto_rawDescOnce sync.Once
	file_storeshare_proto_rawDescData []byte
)

func file_storeshare_proto_rawDescGZIP() []byte {
	file_storeshare_proto_rawDescOnce.Do(func() {
		file_storeshare_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storeshare_proto_rawDesc), len(file_storeshare_proto_rawDesc)))
	})
	return file_storeshare_proto_rawDescData
}

var file_storeshare_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_storeshare_proto_goTypes = []any{
	(*StoreShareRequestMessage)(nil),  // 0: org.derecalliance.derec.protobuf.StoreShareRequestMessage
	(*StoreShareResponseMessage)(nil), // 1: org.derecalliance.derec.protobuf.StoreShareResponseMessage
	(*timestamppb.Timestamp)(nil),     // 2: google.protobuf.Timestamp
	(*TransportProtocol)(nil),         // 3: org.derecalliance.derec.protobuf.TransportProtocol
	(*DeRecResult)(nil),               // 4: org.derecalliance.derec.protobuf.DeRecResult
}
var file_storeshare_proto_depIdxs = []int32{
	2, // 0: org.derecalliance.derec.protobuf.StoreShareRequestMessage.timestamp:type_name -> google.protobuf.Timestamp
	3, // 1: org.derecalliance.derec.protobuf.StoreShareRequestMessage.replyTo:type_name -> org.derecalliance.derec.protobuf.TransportProtocol
	3, // 2: org.derecalliance.derec.protobuf.StoreShareRequestMessage.replyToTransports:type_name -> org.derecalliance.derec.protobuf.TransportProtocol
	4, // 3: org.derecalliance.derec.protobuf.StoreShareResponseMessage.result:type_name -> org.derecalliance.derec.protobuf.DeRecResult
	2, // 4: org.derecalliance.derec.protobuf.StoreShareResponseMessage.timestamp:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_storeshare_proto_init() }
func file_storeshare_proto_init() {
	if File_storeshare_proto != nil {
		return
	}
	file_result_proto_init()
	file_transportprotocol_proto_init()
	file_storeshare_proto_msgTypes[0].OneofWrappers = []any{}
	file_storeshare_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storeshare_proto_rawDesc), len(file_storeshare_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storeshare_proto_goTypes,
		DependencyIndexes: file_storeshare_proto_depIdxs,
		MessageInfos:      file_storeshare_proto_msgTypes,
	}.Build()
	File_storeshare_proto = out.File
	file_storeshare_proto_goTypes = nil
	file_storeshare_proto_depIdxs = nil
}
