//
// Copyright (c) DeRec Alliance and its Contributors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: transportprotocol.proto

package derecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// / Enumeration of supported transport protocols.
// /
// / Additional values MAY be introduced in future versions of the protocol.
type Protocol int32

const (
	// / HTTPS-based transport.
	// /
	// / Messages are delivered via HTTP(S) requests, typically using a
	// / request/response pattern where the Owner acts as client and the
	// / Helper acts as server.
	// /
	// / This is the default and currently required transport.
	Protocol_HTTPS Protocol = 0
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "HTTPS",
	}
	Protocol_value = map[string]int32{
		"HTTPS": 0,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_transportprotocol_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_transportprotocol_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_transportprotocol_proto_rawDescGZIP(), []int{0}
}

// / TransportProtocol defines how a DeRec participant (Owner or Helper)
// / can be reached over the network.
// /
// / This message encapsulates the transport-layer endpoint and the protocol
// / required to deliver DeRec messages to that endpoint. It is typically
// / exchanged during pairing (via ContactMessage) so that both parties know
// / how to establish communication channels.
// /
// / A TransportProtocol does not itself provide security guarantees.
// / All DeRec protocol messages MUST still be signed and encrypted at the
// / application layer, regardless of the underlying transport.
// /
// / # Semantics
// /
// / - The `uri` identifies the remote endpoint (e.g., HTTPS URL, message queue).
// / - The `protocol` specifies how the URI should be interpreted and how
// /   messages must be transmitted.
// / - The combination of (`protocol`, `uri`) MUST be sufficient for the sender
// /   to deliver a DeRec message to the receiver.
// /
// / # Usage
// /
// / - Included in ContactMessage during pairing to advertise reachable endpoints.
// / - May be stored by peers as part of the communication channel state.
// / - Used by the sender to select the correct transport mechanism when
// /   delivering protocol messages.
// /
// / # Extensibility
// /
// / The Protocol enum is expected to grow as new transport mechanisms are
// / supported (e.g., message queues, peer-to-peer transports). Implementations
// / MUST ignore unknown enum values unless explicitly required otherwise.
// /
// / # Reliability
// /
// / Transport protocols may be:
// / - request/response (e.g., HTTPS)
// / - store-and-forward (e.g., message queues)
// /
// / Implementations MUST handle retries and idempotency at the protocol layer,
// / independent of transport guarantees.
type TransportProtocol struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / URI endpoint used to contact the peer.
	// /
	// / The format of this field depends on the selected `protocol`.
	// / Examples:
	// /
	// / - HTTPS: "https://example.com/derec"
	// / - Future protocols MAY define other URI schemes.
	// /
	// / The URI MUST be sufficient to route messages to the intended recipient.
	Uri string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	// / Transport protocol associated with the URI.
	// /
	// / This determines:
	// / - how the `uri` should be interpreted
	// / - how messages are serialized and delivered
	// / - what communication pattern is expected (e.g., synchronous vs async)
	// /
	// / Implementations MUST support all mandatory protocol types defined here.
	Protocol      Protocol `protobuf:"varint,2,opt,name=protocol,proto3,enum=org.derecalliance.derec.protobuf.Protocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransportProtocol) Reset() {
	*x = TransportProtocol{}
	mi := &file_transportprotocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportProtocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportProtocol) ProtoMessage() {}

func (x *TransportProtocol) ProtoReflect() protoreflect.Message {
	mi := &file_transportprotocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportProtocol.ProtoReflect.Descriptor instead.
func (*TransportProtocol) Descriptor() ([]byte, []int) {
	return file_transportprotocol_proto_rawDescGZIP(), []int{0}
}

func (x *TransportProtocol) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *TransportProtocol) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_HTTPS
}

var File_transportprotocol_proto protoreflect.FileDescriptor

const file_transportprotocol_proto_rawDesc = "" +
	"\n" +
	"\x17transportprotocol.proto\x12 org.derecalliance.derec.protobuf\"m\n" +
	"\x11TransportProtocol\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12F\n" +
	"\bprotocol\x18\x02 \x01(\x0e2*.org.derecalliance.derec.protobuf.ProtocolR\bprotocol*\x15\n" +
	"\bProtocol\x12\t\n" +
	"\x05HTTPS\x10\x00b\x06proto3"

var (
	file_transportprotocol_proto_rawDescOnce sync.Once
	file_transportprotocol_proto_rawDescData []byte
)

func file_transportprotocol_proto_rawDescGZIP() []byte {
	file_transportprotocol_proto_rawDescOnce.Do(func() {
		file_transportprotocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transportprotocol_proto_rawDesc), len(file_transportprotocol_proto_rawDesc)))
	})
	return file_transportprotocol_proto_rawDescData
}

var file_transportprotocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transportprotocol_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transportprotocol_proto_goTypes = []any{
	(Protocol)(0),             // 0: org.derecalliance.derec.protobuf.Protocol
	(*TransportProtocol)(nil), // 1: org.derecalliance.derec.protobuf.TransportProtocol
}
var file_transportprotocol_proto_depIdxs = []int32{
	0, // 0: org.derecalliance.derec.protobuf.TransportProtocol.protocol:type_name -> org.derecalliance.derec.protobuf.Protocol
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transportprotocol_proto_init() }
func file_transportprotocol_proto_init() {
	if File_transportprotocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transportprotocol_proto_rawDesc), len(file_transportprotocol_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transportprotocol_proto_goTypes,
		DependencyIndexes: file_transportprotocol_proto_depIdxs,
		EnumInfos:         file_transportprotocol_proto_enumTypes,
		MessageInfos:      file_transportprotocol_proto_msgTypes,
	}.Build()
	File_transportprotocol_proto = out.File
	file_transportprotocol_proto_goTypes = nil
	file_transportprotocol_proto_depIdxs = nil
}
