//
// Copyright (c) DeRec Alliance and its Contributors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: unpair.proto

package derecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UnpairRequestMessage requests termination of the DeRec relationship
// between two parties (Owner and Helper).
//
// # Context
//
// This message is used when:
//
// - the Owner no longer wants a Helper to store shares
// - the Helper chooses to stop acting as a Helper
// - the relationship must be terminated due to policy, failure, or user action
//
// # Semantics
//
// Upon receiving this message, the recipient MUST:
//
// - stop acting as a Helper for the corresponding channel
// - cease all protocol interactions for that channel
//
// The recipient SHOULD:
//
// - delete all stored shares and related state for the Owner
//
// However, deletion MAY be subject to:
//
// - regulatory requirements
// - contractual obligations
// - service-specific retention policies
//
// # Effects on Protocol State
//
// After a successful unpair:
//
// - the channel is considered permanently closed
// - the Owner MUST NOT rely on this Helper for recovery
// - the Owner SHOULD reshare secrets with remaining Helpers if necessary
//
// # Idempotency
//
// This message is idempotent. Repeated unpair requests SHOULD result in
// the same final state.
type UnpairRequestMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional human-readable explanation for the unpairing.
	//
	// This field is intended for logging, debugging, or user display.
	// It MUST NOT be relied upon for protocol behavior.
	Memo string `protobuf:"bytes,1,opt,name=memo,proto3" json:"memo,omitempty"`
	// Timestamp indicating when this message was created.
	//
	// This value is expressed in UTC and can be used for:
	//
	// - observability and logging
	// - replay detection (in combination with sequence numbers)
	// - timeout handling
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Ephemeral transport endpoint at which the requester wants to receive
	// the response to *this exchange*, overriding the channel's stored peer
	// endpoint for this round-trip only.
	//
	// See `StoreShareRequestMessage.replyTo` for full semantics. Absent =
	// route to the stored channel endpoint; Present = route this response
	// here without persisting the endpoint.
	ReplyTo *TransportProtocol `protobuf:"bytes,3,opt,name=replyTo,proto3,oneof" json:"replyTo,omitempty"`
	// Identity of the replica-group member that initiated this unpair.
	//
	// A replica-originated unpair MUST carry it; an owner-originated one MUST
	// NOT. Its presence is what tells the receiver which path the message
	// belongs to, exactly as on `StoreShareRequestMessage`. Asserted on send
	// and on receive; a violation is a protocol error.
	//
	// Removing a replica is not the same operation as unpairing a helper. A
	// helper channel serves exactly one peer, so unpairing deletes it. Every
	// member of a replica group shares one channel, so deleting it would sever
	// the whole group — replica removal edits a member row instead, and this
	// field says which row.
	ReplicaId     *uint64 `protobuf:"varint,4,opt,name=replicaId,proto3,oneof" json:"replicaId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpairRequestMessage) Reset() {
	*x = UnpairRequestMessage{}
	mi := &file_unpair_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpairRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpairRequestMessage) ProtoMessage() {}

func (x *UnpairRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_unpair_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpairRequestMessage.ProtoReflect.Descriptor instead.
func (*UnpairRequestMessage) Descriptor() ([]byte, []int) {
	return file_unpair_proto_rawDescGZIP(), []int{0}
}

func (x *UnpairRequestMessage) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *UnpairRequestMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *UnpairRequestMessage) GetReplyTo() *TransportProtocol {
	if x != nil {
		return x.ReplyTo
	}
	return nil
}

func (x *UnpairRequestMessage) GetReplicaId() uint64 {
	if x != nil && x.ReplicaId != nil {
		return *x.ReplicaId
	}
	return 0
}

// UnpairResponseMessage is the response to an UnpairRequestMessage.
//
// # Semantics
//
// This message indicates whether the recipient successfully processed
// the unpair request.
//
// On success:
//
// - the relationship is considered terminated
// - the recipient has ceased participation in the protocol for this channel
//
// On failure:
//
//   - the relationship state is undefined and SHOULD be handled by the
//     application (e.g., retry or escalate)
//
// # Idempotency
//
// Multiple identical unpair requests SHOULD produce consistent responses.
type UnpairResponseMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result of processing the unpair request.
	//
	// Indicates whether the unpair operation was successfully completed.
	Result *DeRecResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// Timestamp indicating when this message was created.
	//
	// This value is expressed in UTC and can be used for:
	//
	// - observability and logging
	// - replay detection (in combination with sequence numbers)
	// - timeout handling
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpairResponseMessage) Reset() {
	*x = UnpairResponseMessage{}
	mi := &file_unpair_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpairResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpairResponseMessage) ProtoMessage() {}

func (x *UnpairResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_unpair_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpairResponseMessage.ProtoReflect.Descriptor instead.
func (*UnpairResponseMessage) Descriptor() ([]byte, []int) {
	return file_unpair_proto_rawDescGZIP(), []int{1}
}

func (x *UnpairResponseMessage) GetResult() *DeRecResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UnpairResponseMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_unpair_proto protoreflect.FileDescriptor

const file_unpair_proto_rawDesc = "" +
	"\n" +
	"\funpair.proto\x12 org.derecalliance.derec.protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fresult.proto\x1a\x17transportprotocol.proto\"\xf5\x01\n" +
	"\x14UnpairRequestMessage\x12\x12\n" +
	"\x04memo\x18\x01 \x01(\tR\x04memo\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12R\n" +
	"\areplyTo\x18\x03 \x01(\v23.org.derecalliance.derec.protobuf.TransportProtocolH\x00R\areplyTo\x88\x01\x01\x12!\n" +
	"\treplicaId\x18\x04 \x01(\x04H\x01R\treplicaId\x88\x01\x01B\n" +
	"\n" +
	"\b_replyToB\f\n" +
	"\n" +
	"_replicaId\"\x98\x01\n" +
	"\x15UnpairResponseMessage\x12E\n" +
	"\x06result\x18\x01 \x01(\v2-.org.derecalliance.derec.protobuf.DeRecResultR\x06result\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampb\x06proto3"

var (
	file_unpair_proto_rawDescOnce sync.Once
	file_unpair_proto_rawDescData []byte
)

func file_unpair_proto_rawDescGZIP() []byte {
	file_unpair_proto_rawDescOnce.Do(func() {
		file_unpair_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_unpair_proto_rawDesc), len(file_unpair_proto_rawDesc)))
	})
	return file_unpair_proto_rawDescData
}

var file_unpair_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_unpair_proto_goTypes = []any{
	(*UnpairRequestMessage)(nil),  // 0: org.derecalliance.derec.protobuf.UnpairRequestMessage
	(*UnpairResponseMessage)(nil), // 1: org.derecalliance.derec.protobuf.UnpairResponseMessage
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*TransportProtocol)(nil),     // 3: org.derecalliance.derec.protobuf.TransportProtocol
	(*DeRecResult)(nil),           // 4: org.derecalliance.derec.protobuf.DeRecResult
}
var file_unpair_proto_depIdxs = []int32{
	2, // 0: org.derecalliance.derec.protobuf.UnpairRequestMessage.timestamp:type_name -> google.protobuf.Timestamp
	3, // 1: org.derecalliance.derec.protobuf.UnpairRequestMessage.replyTo:type_name -> org.derecalliance.derec.protobuf.TransportProtocol
	4, // 2: org.derecalliance.derec.protobuf.UnpairResponseMessage.result:type_name -> org.derecalliance.derec.protobuf.DeRecResult
	2, // 3: org.derecalliance.derec.protobuf.UnpairResponseMessage.timestamp:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_unpair_proto_init() }
func file_unpair_proto_init() {
	if File_unpair_proto != nil {
		return
	}
	file_result_proto_init()
	file_transportprotocol_proto_init()
	file_unpair_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_unpair_proto_rawDesc), len(file_unpair_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_unpair_proto_goTypes,
		DependencyIndexes: file_unpair_proto_depIdxs,
		MessageInfos:      file_unpair_proto_msgTypes,
	}.Build()
	File_unpair_proto = out.File
	file_unpair_proto_goTypes = nil
	file_unpair_proto_depIdxs = nil
}
