//
// Copyright (c) DeRec Alliance and its Contributors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: updatechannelinfo.proto

package derecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UpdateChannelInfoRequestMessage notifies the peer that the sender's
// communication metadata and/or transport endpoint have changed.
//
// # Context
//
// Both `communication_info` and `transport_protocol` are exchanged at pairing
// time only. This message lets either party (Owner or Helper) propagate
// post-pairing changes without re-pairing.
//
// # Semantics
//
// Both fields are optional and independent:
//
//   - `communication_info` absent (no `CommunicationInfo` set) means "do not
//     modify the communication info stored for the sender." Presence — even
//     with an empty `communication_info_entries` list — means "replace the
//     stored map with the supplied one." Updates, additions, and deletions
//     are all expressed by the difference between the receiver's current map
//     and the supplied one.
//   - `transport_protocol` absent means "do not modify the transport endpoint
//     stored for the sender." Presence means "the sender's transport endpoint
//     is now this value." The receiver MUST route subsequent messages on this
//     channel to the new endpoint, including the
//     UpdateChannelInfoResponseMessage for this request.
//
// # Endpoint changeover
//
// When `transport_protocol` is updated, the receiver sends its response to
// the new endpoint. The sender's application is therefore responsible for
// ensuring the new endpoint is reachable BEFORE this request is issued, and
// for keeping the old endpoint operational long enough for in-flight
// messages from other peers (and any concurrent operations) to drain.
type UpdateChannelInfoRequestMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated communication info for the sender, or absent to leave unchanged.
	//
	// Presence (even with an empty entries list) replaces the receiver's
	// stored map for this channel. Absence leaves it untouched.
	CommunicationInfo *CommunicationInfo `protobuf:"bytes,1,opt,name=communicationInfo,proto3,oneof" json:"communicationInfo,omitempty"`
	// Updated transport endpoint for the sender, or absent to leave unchanged.
	//
	// Presence updates both the URI and protocol enum. The receiver routes
	// the response to this new endpoint.
	//
	// Deprecated: superseded by `supportedTransports`, which carries every
	// endpoint rather than one.
	//
	// **Reading this field directly is now incorrect.** Its meaning narrowed
	// from "the endpoint" to "one entry of a list, and possibly absent": a
	// sender that has moved past this field announces only
	// `supportedTransports`. A reader that was correct before this release is
	// a bug now — it records the wrong address, or none, for a peer that
	// announced a perfectly good one. Resolve both spellings instead of
	// reading either: `advertised_endpoints()` (Rust and TypeScript),
	// `AdvertisedEndpoints()` (Go), `AdvertisedEndpoints()` (.NET).
	//
	// Senders still populate it: a sender that sets `supportedTransports`
	// MUST also set this to a single best-compatibility choice, so
	// implementations predating the list still learn the new address.
	//
	// **Scheduled for removal in v0.0.5.**
	//
	// Deprecated: Marked as deprecated in updatechannelinfo.proto.
	TransportProtocol *TransportProtocol `protobuf:"bytes,2,opt,name=transportProtocol,proto3,oneof" json:"transportProtocol,omitempty"`
	// Every transport endpoint the sender can now be reached on, in its own
	// preference order, replacing the receiver's stored set for this channel.
	//
	// # Semantics
	//
	//   - Empty, and `transportProtocol` absent: the sender's endpoints are
	//     left unchanged. An update that changes only `communicationInfo` says
	//     nothing about transports.
	//   - Non-empty: replaces the stored set outright. Unlike a request's
	//     `replyTo`, this **is** persisted — it is how a peer announces it has
	//     moved.
	//
	// # Compatibility
	//
	// Empty with `transportProtocol` present means "only that one endpoint is
	// offered", which is how every implementation predating this field
	// behaves. A sender populating this list MUST also set
	// `transportProtocol` to a single best-compatibility choice so those
	// implementations still learn the new address.
	SupportedTransports []*TransportProtocol `protobuf:"bytes,4,rep,name=supportedTransports,proto3" json:"supportedTransports,omitempty"`
	// Timestamp indicating when this message was created.
	//
	// This value is expressed in UTC and is used for envelope-vs-body
	// timestamp validation, replay detection, and observability.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChannelInfoRequestMessage) Reset() {
	*x = UpdateChannelInfoRequestMessage{}
	mi := &file_updatechannelinfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChannelInfoRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChannelInfoRequestMessage) ProtoMessage() {}

func (x *UpdateChannelInfoRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_updatechannelinfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChannelInfoRequestMessage.ProtoReflect.Descriptor instead.
func (*UpdateChannelInfoRequestMessage) Descriptor() ([]byte, []int) {
	return file_updatechannelinfo_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateChannelInfoRequestMessage) GetCommunicationInfo() *CommunicationInfo {
	if x != nil {
		return x.CommunicationInfo
	}
	return nil
}

// Deprecated: Marked as deprecated in updatechannelinfo.proto.
func (x *UpdateChannelInfoRequestMessage) GetTransportProtocol() *TransportProtocol {
	if x != nil {
		return x.TransportProtocol
	}
	return nil
}

func (x *UpdateChannelInfoRequestMessage) GetSupportedTransports() []*TransportProtocol {
	if x != nil {
		return x.SupportedTransports
	}
	return nil
}

func (x *UpdateChannelInfoRequestMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// UpdateChannelInfoResponseMessage is the response to an
// UpdateChannelInfoRequestMessage.
//
// # Semantics
//
// On success (`result.status == OK`):
//
//   - the receiver has persisted the supplied updates
//   - subsequent messages from the receiver MUST use the new endpoint, if
//     `transport_protocol` was updated
//
// On failure:
//
// - the receiver's stored state is unchanged
// - the sender SHOULD inspect `result.memo` for diagnostic context
type UpdateChannelInfoResponseMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result of processing the update.
	Result *DeRecResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// Timestamp indicating when this message was created.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChannelInfoResponseMessage) Reset() {
	*x = UpdateChannelInfoResponseMessage{}
	mi := &file_updatechannelinfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChannelInfoResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChannelInfoResponseMessage) ProtoMessage() {}

func (x *UpdateChannelInfoResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_updatechannelinfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChannelInfoResponseMessage.ProtoReflect.Descriptor instead.
func (*UpdateChannelInfoResponseMessage) Descriptor() ([]byte, []int) {
	return file_updatechannelinfo_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateChannelInfoResponseMessage) GetResult() *DeRecResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UpdateChannelInfoResponseMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_updatechannelinfo_proto protoreflect.FileDescriptor

const file_updatechannelinfo_proto_rawDesc = "" +
	"\n" +
	"\x17updatechannelinfo.proto\x12 org.derecalliance.derec.protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17communicationinfo.proto\x1a\fresult.proto\x1a\x17transportprotocol.proto\"\xc2\x03\n" +
	"\x1fUpdateChannelInfoRequestMessage\x12f\n" +
	"\x11communicationInfo\x18\x01 \x01(\v23.org.derecalliance.derec.protobuf.CommunicationInfoH\x00R\x11communicationInfo\x88\x01\x01\x12j\n" +
	"\x11transportProtocol\x18\x02 \x01(\v23.org.derecalliance.derec.protobuf.TransportProtocolB\x02\x18\x01H\x01R\x11transportProtocol\x88\x01\x01\x12e\n" +
	"\x13supportedTransports\x18\x04 \x03(\v23.org.derecalliance.derec.protobuf.TransportProtocolR\x13supportedTransports\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB\x14\n" +
	"\x12_communicationInfoB\x14\n" +
	"\x12_transportProtocol\"\xa3\x01\n" +
	" UpdateChannelInfoResponseMessage\x12E\n" +
	"\x06result\x18\x01 \x01(\v2-.org.derecalliance.derec.protobuf.DeRecResultR\x06result\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampb\x06proto3"

var (
	file_updatechannelinfo_proto_rawDescOnce sync.Once
	file_updatechannelinfo_proto_rawDescData []byte
)

func file_updatechannelinfo_proto_rawDescGZIP() []byte {
	file_updatechannelinfo_proto_rawDescOnce.Do(func() {
		file_updatechannelinfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_updatechannelinfo_proto_rawDesc), len(file_updatechannelinfo_proto_rawDesc)))
	})
	return file_updatechannelinfo_proto_rawDescData
}

var file_updatechannelinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_updatechannelinfo_proto_goTypes = []any{
	(*UpdateChannelInfoRequestMessage)(nil),  // 0: org.derecalliance.derec.protobuf.UpdateChannelInfoRequestMessage
	(*UpdateChannelInfoResponseMessage)(nil), // 1: org.derecalliance.derec.protobuf.UpdateChannelInfoResponseMessage
	(*CommunicationInfo)(nil),                // 2: org.derecalliance.derec.protobuf.CommunicationInfo
	(*TransportProtocol)(nil),                // 3: org.derecalliance.derec.protobuf.TransportProtocol
	(*timestamppb.Timestamp)(nil),            // 4: google.protobuf.Timestamp
	(*DeRecResult)(nil),                      // 5: org.derecalliance.derec.protobuf.DeRecResult
}
var file_updatechannelinfo_proto_depIdxs = []int32{
	2, // 0: org.derecalliance.derec.protobuf.UpdateChannelInfoRequestMessage.communicationInfo:type_name -> org.derecalliance.derec.protobuf.CommunicationInfo
	3, // 1: org.derecalliance.derec.protobuf.UpdateChannelInfoRequestMessage.transportProtocol:type_name -> org.derecalliance.derec.protobuf.TransportProtocol
	3, // 2: org.derecalliance.derec.protobuf.UpdateChannelInfoRequestMessage.supportedTransports:type_name -> org.derecalliance.derec.protobuf.TransportProtocol
	4, // 3: org.derecalliance.derec.protobuf.UpdateChannelInfoRequestMessage.timestamp:type_name -> google.protobuf.Timestamp
	5, // 4: org.derecalliance.derec.protobuf.UpdateChannelInfoResponseMessage.result:type_name -> org.derecalliance.derec.protobuf.DeRecResult
	4, // 5: org.derecalliance.derec.protobuf.UpdateChannelInfoResponseMessage.timestamp:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_updatechannelinfo_proto_init() }
func file_updatechannelinfo_proto_init() {
	if File_updatechannelinfo_proto != nil {
		return
	}
	file_communicationinfo_proto_init()
	file_result_proto_init()
	file_transportprotocol_proto_init()
	file_updatechannelinfo_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_updatechannelinfo_proto_rawDesc), len(file_updatechannelinfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_updatechannelinfo_proto_goTypes,
		DependencyIndexes: file_updatechannelinfo_proto_depIdxs,
		MessageInfos:      file_updatechannelinfo_proto_msgTypes,
	}.Build()
	File_updatechannelinfo_proto = out.File
	file_updatechannelinfo_proto_goTypes = nil
	file_updatechannelinfo_proto_depIdxs = nil
}
