//
// Copyright (c) DeRec Alliance and its Contributors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: verify.proto

package derecpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VerifyShareRequestMessage initiates a verification challenge from the Owner
// to a Helper to confirm that the Helper still retains a specific share.
//
// # Context
//
// This message is part of the verification flow, which allows the Owner to:
//
// - periodically check Helper liveness
// - detect data loss or corruption of stored shares
// - identify Helpers that are no longer reliable for recovery
//
// # Semantics
//
// The Owner challenges the Helper by providing:
//
// - a `version` identifying the share to verify
// - a fresh `nonce` to ensure the response is unique and not replayable
//
// The Helper MUST compute a cryptographic hash over:
//
//	committedDeRecShare || nonce
//
// and return the result in a VerifyShareResponseMessage.
//
// # Security Properties
//
// - The nonce ensures freshness and prevents replay attacks
// - The hash proves possession of the exact share bytes
// - The Helper cannot produce a valid response without holding the share
//
// # Idempotency
//
// Each request is uniquely identified by the nonce. Reusing a nonce SHOULD
// be avoided, as it weakens replay protection guarantees.
type VerifyShareRequestMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Secret id being challenged.
	//
	// This identifies which stored share for a secret the Helper must use to compute
	// the verification proof.
	SecretId uint64 `protobuf:"varint,1,opt,name=secretId,proto3" json:"secretId,omitempty"`
	// Share version being challenged.
	//
	// This identifies which stored share version the Helper must use to compute
	// the verification proof.
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// Random challenge nonce generated by the Owner.
	//
	// This value MUST be unpredictable and unique per request to ensure
	// freshness and prevent replay of previous responses.
	Nonce uint64 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Timestamp indicating when this message was created.
	//
	// This value is expressed in UTC and can be used for:
	//
	// - observability and logging
	// - replay detection (in combination with sequence numbers)
	// - timeout handling
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Ephemeral transport endpoint at which the requester wants to receive
	// the response to *this exchange*, overriding the channel's stored peer
	// endpoint for this round-trip only.
	//
	// See `StoreShareRequestMessage.replyTo` for full semantics. Absent =
	// route to the stored channel endpoint; Present = route this response
	// here without persisting the endpoint.
	ReplyTo       *TransportProtocol `protobuf:"bytes,5,opt,name=replyTo,proto3,oneof" json:"replyTo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyShareRequestMessage) Reset() {
	*x = VerifyShareRequestMessage{}
	mi := &file_verify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyShareRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyShareRequestMessage) ProtoMessage() {}

func (x *VerifyShareRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_verify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyShareRequestMessage.ProtoReflect.Descriptor instead.
func (*VerifyShareRequestMessage) Descriptor() ([]byte, []int) {
	return file_verify_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyShareRequestMessage) GetSecretId() uint64 {
	if x != nil {
		return x.SecretId
	}
	return 0
}

func (x *VerifyShareRequestMessage) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VerifyShareRequestMessage) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *VerifyShareRequestMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *VerifyShareRequestMessage) GetReplyTo() *TransportProtocol {
	if x != nil {
		return x.ReplyTo
	}
	return nil
}

// VerifyShareResponseMessage contains the result of a verification challenge
// and, on success, provides a proof of share possession.
//
// # Semantics
//
// In response to a VerifyShareRequestMessage, the Helper:
//
// - retrieves the requested share version
// - computes the hash over (committedDeRecShare || nonce)
// - returns the result along with the echoed version and nonce
//
// The Owner verifies the response by recomputing the expected hash and
// comparing it with the received value.
//
// # Failure Handling
//
// If the verification fails (e.g., incorrect hash or error result), the Owner:
//
// - MAY retry the verification
// - MAY resend the correct share to the Helper
// - MAY mark the Helper as unreliable after repeated failures
//
// # Security Considerations
//
// - The hash MUST be computed using SHA-384 as defined by the protocol
// - The nonce MUST match the request to ensure the response is not replayed
// - The response MUST be sent over an authenticated and encrypted channel
//
// # Idempotency
//
// Responses are tied to a specific (version, nonce) pair. Replaying a response
// with a stale nonce SHOULD be rejected by the Owner.
type VerifyShareResponseMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result of processing the verification request.
	//
	// Indicates whether the Helper successfully computed the proof or
	// encountered an error (e.g., share not found).
	Result *DeRecResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// Secret id this response refers to.
	//
	// MUST match the version provided in the request.
	SecretId uint64 `protobuf:"varint,2,opt,name=secretId,proto3" json:"secretId,omitempty"`
	// Share version this response refers to.
	//
	// MUST match the version provided in the request.
	Version uint32 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// Challenge nonce echoed from the request.
	//
	// MUST exactly match the nonce provided in the request.
	Nonce uint64 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Verification proof.
	//
	// This is the SHA-384 hash of:
	//
	//	committedDeRecShare || nonce
	//
	// where `committedDeRecShare` is the exact byte sequence originally
	// stored by the Helper.
	Hash []byte `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	// Timestamp indicating when this message was created.
	//
	// This value is expressed in UTC and can be used for:
	//
	// - observability and logging
	// - replay detection (in combination with sequence numbers)
	// - timeout handling
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyShareResponseMessage) Reset() {
	*x = VerifyShareResponseMessage{}
	mi := &file_verify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyShareResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyShareResponseMessage) ProtoMessage() {}

func (x *VerifyShareResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_verify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyShareResponseMessage.ProtoReflect.Descriptor instead.
func (*VerifyShareResponseMessage) Descriptor() ([]byte, []int) {
	return file_verify_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyShareResponseMessage) GetResult() *DeRecResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *VerifyShareResponseMessage) GetSecretId() uint64 {
	if x != nil {
		return x.SecretId
	}
	return 0
}

func (x *VerifyShareResponseMessage) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VerifyShareResponseMessage) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *VerifyShareResponseMessage) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *VerifyShareResponseMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_verify_proto protoreflect.FileDescriptor

const file_verify_proto_rawDesc = "" +
	"\n" +
	"\fverify.proto\x12 org.derecalliance.derec.protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fresult.proto\x1a\x17transportprotocol.proto\"\x81\x02\n" +
	"\x19VerifyShareRequestMessage\x12\x1a\n" +
	"\bsecretId\x18\x01 \x01(\x04R\bsecretId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\x04R\x05nonce\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12R\n" +
	"\areplyTo\x18\x05 \x01(\v23.org.derecalliance.derec.protobuf.TransportProtocolH\x00R\areplyTo\x88\x01\x01B\n" +
	"\n" +
	"\b_replyTo\"\xfd\x01\n" +
	"\x1aVerifyShareResponseMessage\x12E\n" +
	"\x06result\x18\x01 \x01(\v2-.org.derecalliance.derec.protobuf.DeRecResultR\x06result\x12\x1a\n" +
	"\bsecretId\x18\x02 \x01(\x04R\bsecretId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\x04R\x05nonce\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\fR\x04hash\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampb\x06proto3"

var (
	file_verify_proto_rawDescOnce sync.Once
	file_verify_proto_rawDescData []byte
)

func file_verify_proto_rawDescGZIP() []byte {
	file_verify_proto_rawDescOnce.Do(func() {
		file_verify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_verify_proto_rawDesc), len(file_verify_proto_rawDesc)))
	})
	return file_verify_proto_rawDescData
}

var file_verify_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_verify_proto_goTypes = []any{
	(*VerifyShareRequestMessage)(nil),  // 0: org.derecalliance.derec.protobuf.VerifyShareRequestMessage
	(*VerifyShareResponseMessage)(nil), // 1: org.derecalliance.derec.protobuf.VerifyShareResponseMessage
	(*timestamppb.Timestamp)(nil),      // 2: google.protobuf.Timestamp
	(*TransportProtocol)(nil),          // 3: org.derecalliance.derec.protobuf.TransportProtocol
	(*DeRecResult)(nil),                // 4: org.derecalliance.derec.protobuf.DeRecResult
}
var file_verify_proto_depIdxs = []int32{
	2, // 0: org.derecalliance.derec.protobuf.VerifyShareRequestMessage.timestamp:type_name -> google.protobuf.Timestamp
	3, // 1: org.derecalliance.derec.protobuf.VerifyShareRequestMessage.replyTo:type_name -> org.derecalliance.derec.protobuf.TransportProtocol
	4, // 2: org.derecalliance.derec.protobuf.VerifyShareResponseMessage.result:type_name -> org.derecalliance.derec.protobuf.DeRecResult
	2, // 3: org.derecalliance.derec.protobuf.VerifyShareResponseMessage.timestamp:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_verify_proto_init() }
func file_verify_proto_init() {
	if File_verify_proto != nil {
		return
	}
	file_result_proto_init()
	file_transportprotocol_proto_init()
	file_verify_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_verify_proto_rawDesc), len(file_verify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_verify_proto_goTypes,
		DependencyIndexes: file_verify_proto_depIdxs,
		MessageInfos:      file_verify_proto_msgTypes,
	}.Build()
	File_verify_proto = out.File
	file_verify_proto_goTypes = nil
	file_verify_proto_depIdxs = nil
}
